// Package authn provides an engine-agnostic Kratos middleware dispatcher for
// authentication. The main package is a pure dispatcher: it knows nothing
// about credential carriers (Bearer token, mTLS PeerCertificate, API-Key
// header, signature, etc.). Engine sub-packages (e.g. `security/authn/jwt`)
// are responsible for credential I/O.
//
// Dispatcher form (P0-4b):
//
//	authn.Server(
//	    authn.Multi(
//	        authn.Named(jwt.Scheme,    jwt.NewAuthenticator(...)),
//	        authn.Named(apikey.Scheme, apikey.NewAuthenticator(...)),
//	    ),
//	    authn.WithRulesFuncs(examplev1.AuthnRules, iamv1.AuthnRules),
//	)
//
// `authn.Server` itself is engine-agnostic: it consumes the annotation table
// (`Rules`) generated by `protoc-gen-servora-authn` to decide for each RPC
// path whether to skip (PublicMethods), restrict to a subset of schemes
// (MethodSchemes), or fail-open across all engines (unannotated).
//
// `authn.Multi` is the standard decorator over multiple `NamedAuthenticator`
// instances. It treats ErrNoCredentials as "try the next allowed engine" and
// treats any other error as fail-fast.
//
// On success the enriched context returned by the engine is passed directly
// to the handler. On failure an optional `WithAuditOnFailure` auditor emits
// a CloudEvents event; the dispatcher itself does not write to the legacy
// auditpb detail holder.
package authn

import (
	"context"
	"fmt"
	"strings"

	cloudevents "github.com/cloudevents/sdk-go/v2"
	"github.com/go-kratos/kratos/v3/errors"
	"github.com/go-kratos/kratos/v3/middleware"
	"github.com/go-kratos/kratos/v3/transport"

	"github.com/Servora-Kit/servora/obs/audit"
)

// Authenticator is the interface for authenticating incoming requests.
//
// CONTRACT: this interface intentionally contains ONLY behavior body
// (`Authenticate`). Engine metadata belongs to the wrapper layer via
// `authn.Named(scheme, a)` — NOT on the interface itself.
//
// What MUST NOT live on this interface:
//   - Engine metadata (e.g. `Method() string`) — supplied by `authn.Named`
//     when wiring `authn.Multi`; framework main package is agnostic to the
//     scheme string.
//   - Hooks / callbacks (e.g. `OnSuccess`) — caller responsibility.
//   - Injection (logger / tracer) — container responsibility.
//   - Infra probes (e.g. `Health`) — separate sibling interface.
//
// This single-method shape prevents interface bloat as new engines (mTLS,
// API-Key, AK+SK, Passkey, etc.) are added: each engine is described to
// the dispatcher by `Named` at wiring time, and orchestration is the
// `Multi` decorator's responsibility.
type Authenticator interface {
	Authenticate(ctx context.Context) (context.Context, error)
}

// Rules is the aggregate authentication-rules table consumed by `Server`.
// It is produced by `protoc-gen-servora-authn` per generated package
// (e.g. `examplev1.AuthnRules()`) and merged across modules by
// `WithRulesFuncs`.
//
// Two disjoint subsets:
//
//   - PublicMethods — RPC paths annotated `MODE_PUBLIC`; the dispatcher
//     short-circuits before calling the engine.
//   - MethodSchemes — RPC paths annotated `MODE_REQUIRED`, mapped to the
//     accepted scheme list (e.g. `["jwt", "apikey"]`); the dispatcher
//     installs an `allowedSchemes` ctx channel so `Multi` can filter.
//
// An RPC path absent from BOTH maps is unannotated; the dispatcher treats
// it as fail-open (no allowed-set installed; `Multi` tries every engine
// in injection order).
type Rules struct {
	PublicMethods []string
	MethodSchemes map[string][]string
}

// Option configures the Server middleware.
type Option func(*serverConfig)

type serverConfig struct {
	rules        Rules
	errorHandler func(ctx context.Context, err error) error
	auditor      audit.Auditor
}

// WithRulesFuncs registers one or more rule-table generator functions.
// `protoc-gen-servora-authn` emits one `AuthnRules() Rules` per .proto
// package; business code passes them as variadic args to merge across
// modules. Nil entries are skipped (no panic) so business code can pass
// optional generators conditionally.
//
// Merge semantics:
//   - PublicMethods slices are appended in argument order.
//   - MethodSchemes entries from later generators overwrite earlier ones.
//     RPC paths are fully qualified service names; collisions are rare
//     in practice and the last-wins rule lets business code intentionally
//     override a downstream module's annotation if needed.
func WithRulesFuncs(fns ...func() Rules) Option {
	return func(c *serverConfig) {
		for _, fn := range fns {
			if fn == nil {
				continue
			}
			r := fn()
			c.rules.PublicMethods = append(c.rules.PublicMethods, r.PublicMethods...)
			if len(r.MethodSchemes) == 0 {
				continue
			}
			if c.rules.MethodSchemes == nil {
				c.rules.MethodSchemes = make(map[string][]string, len(r.MethodSchemes))
			}
			for k, v := range r.MethodSchemes {
				c.rules.MethodSchemes[k] = v
			}
		}
	}
}

// WithErrorHandler installs a custom error transformer invoked when
// authentication fails. If the underlying error implements
// `SchemeAttemptsErr` (i.e. came from `Multi`), the hook can type-assert
// to retrieve per-scheme attempts.
func WithErrorHandler(h func(ctx context.Context, err error) error) Option {
	return func(c *serverConfig) { c.errorHandler = h }
}

// WithAuditOnFailure installs an Auditor that receives a CloudEvents event
// on every authentication failure. The event carries:
//   - type = "servora.authn.v1.failure"
//   - source = the RPC operation from transport ctx
//   - severity extension = "WARN"
//   - data = error message as text/plain
//
// When no auditor is configured (default), the failure path does not emit.
func WithAuditOnFailure(a audit.Auditor) Option {
	return func(c *serverConfig) { c.auditor = a }
}

// Server returns a Kratos middleware that dispatches authentication to the
// supplied `Authenticator` (typically a `Multi` decorator).
//
// Per-request behavior:
//
//  1. Resolve operation: `transport.FromServerContext(ctx).Operation()`.
//  2. PublicMethods passthrough: if op ∈ `Rules.PublicMethods`, passthrough
//     — do not call the engine.
//  3. Build the allowed-schemes set: if op ∈ `Rules.MethodSchemes`, install
//     `allowed = set(rules.MethodSchemes[op])` into ctx. Otherwise install
//     nil (fail-open / unannotated).
//  4. Call `a.Authenticate(ctx)`.
//  5. Success → use the returned enriched ctx directly, call the handler.
//  6. Failure → optionally emit audit event (if WithAuditOnFailure set),
//     then either invoke `WithErrorHandler` (if set) or return
//     `errors.Unauthorized("AUTHN_FAILED", reason)`.
func Server(a Authenticator, opts ...Option) middleware.Middleware {
	cfg := &serverConfig{}
	for _, opt := range opts {
		opt(cfg)
	}
	publicSet := stringSet(cfg.rules.PublicMethods)

	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			// Step 1: resolve operation (best-effort — may be absent in
			// non-server contexts; dispatch still proceeds with empty op,
			// which means PublicMethods/MethodSchemes lookups miss and the
			// engine receives full fail-open semantics).
			var op string
			if tr, ok := transport.FromServerContext(ctx); ok && tr != nil {
				op = tr.Operation()
			}

			// Step 2: PublicMethods passthrough — engine NOT called.
			// Business handler sees ctx as-is and is expected to treat
			// it as anonymous.
			if _, isPublic := publicSet[op]; isPublic {
				return handler(ctx, req)
			}

			// Step 3: build the allowed-schemes set for Multi to filter on.
			// Absent op → allowed=nil → Multi tries every engine.
			var allowed map[string]struct{}
			if schemes, ok := cfg.rules.MethodSchemes[op]; ok {
				allowed = stringSet(schemes)
			}

			// Step 4: install allowedSchemes before dispatch. `Multi`
			// reads it to filter engines.
			ctx = withAllowedSchemes(ctx, allowed)

			// Step 5: dispatch.
			enrichedCtx, err := a.Authenticate(ctx)

			// Step 6: failure path.
			if err != nil {
				reason := err.Error()
				if as, ok := err.(SchemeAttemptsErr); ok {
					reason = renderSchemeAttempts(as.SchemeAttempts())
				}
				// Emit audit event if auditor is configured.
				if cfg.auditor != nil {
					emitAuthnFailure(ctx, cfg.auditor, op, reason)
				}
				if cfg.errorHandler != nil {
					return nil, cfg.errorHandler(ctx, err)
				}
				return nil, errors.Unauthorized(authnFailedReason, reason)
			}

			// Step 5: success path — use the enriched ctx from engine.
			return handler(enrichedCtx, req)
		}
	}
}

// emitAuthnFailure constructs a CloudEvents event and emits it via the
// configured Auditor. Errors from Emit are silently ignored (audit must
// not break business flow).
func emitAuthnFailure(ctx context.Context, auditor audit.Auditor, op, reason string) {
	event := cloudevents.NewEvent()
	event.SetType("servora.authn.v1.failure")
	event.SetSource(op)
	event.SetExtension("severity", "WARN")
	_ = event.SetData("text/plain", reason)
	_ = auditor.Emit(ctx, event)
}

// authnFailedReason is the kratos error reason used for the default
// `errors.Unauthorized(...)` return when no `WithErrorHandler` is set.
const authnFailedReason = "AUTHN_FAILED"

// renderSchemeAttempts serializes a `[]SchemeAttempt` into the
// "scheme1: reason1; scheme2: reason2" form used in failure responses.
func renderSchemeAttempts(attempts []SchemeAttempt) string {
	if len(attempts) == 0 {
		return ""
	}
	parts := make([]string, 0, len(attempts))
	for _, at := range attempts {
		parts = append(parts, fmt.Sprintf("%s: %s", at.Scheme, at.Reason))
	}
	return strings.Join(parts, "; ")
}

// stringSet builds a set view of a string slice. Returns nil for empty
// input so callers can use `allowed == nil` to mean "no restriction".
func stringSet(xs []string) map[string]struct{} {
	if len(xs) == 0 {
		return nil
	}
	s := make(map[string]struct{}, len(xs))
	for _, x := range xs {
		s[x] = struct{}{}
	}
	return s
}
