// Package authn provides an engine-agnostic Kratos middleware dispatcher for
// authentication. The main package is a pure dispatcher: it knows nothing
// about credential carriers (Bearer token, mTLS PeerCertificate, API-Key
// header, signature, etc.). Engine sub-packages (e.g. `security/authn/jwt`)
// are responsible for credential I/O.
//
// Dispatcher form (P0-4b):
//
//	authn.Server(
//	    authn.Multi(
//	        authn.Named(jwt.Scheme,    jwt.NewAuthenticator(...)),
//	        authn.Named(apikey.Scheme, apikey.NewAuthenticator(...)),
//	    ),
//	    authn.WithRulesFuncs(examplev1.AuthnRules, iamv1.AuthnRules),
//	)
//
// `authn.Server` itself is engine-agnostic: it consumes the AuthnRule map
// generated by `protoc-gen-servora-authn` to decide for each RPC path whether
// to skip (MODE_PUBLIC), restrict to a subset of schemes (MODE_REQUIRED with
// schemes), or try all engines (MODE_REQUIRED without schemes, unannotated).
//
// `authn.Multi` is the standard decorator over multiple `NamedAuthenticator`
// instances. It treats ErrNoCredentials as "try the next allowed engine" and
// treats any other error as fail-fast.
//
// On success the enriched context returned by the engine is passed directly
// to the handler. When configured, the `WithAuditor` auditor emits typed
// CloudEvents for both success and failure.
package authn

import (
	"context"
	"fmt"
	"strings"

	"github.com/go-kratos/kratos/v3/errors"
	"github.com/go-kratos/kratos/v3/middleware"
	"github.com/go-kratos/kratos/v3/transport"

	authnpb "github.com/Servora-Kit/servora/api/gen/go/servora/authn/v1"
	"github.com/Servora-Kit/servora/obs/audit"
)

// Authenticator is the interface for authenticating incoming requests.
//
// CONTRACT: this interface intentionally contains ONLY behavior body
// (`Authenticate`). Engine metadata belongs to the wrapper layer via
// `authn.Named(scheme, a)` — NOT on the interface itself.
//
// What MUST NOT live on this interface:
//   - Engine metadata (e.g. `Method() string`) — supplied by `authn.Named`
//     when wiring `authn.Multi`; framework main package is agnostic to the
//     scheme string.
//   - Hooks / callbacks (e.g. `OnSuccess`) — caller responsibility.
//   - Injection (logger / tracer) — container responsibility.
//   - Infra probes (e.g. `Health`) — separate sibling interface.
//
// This single-method shape prevents interface bloat as new engines (mTLS,
// API-Key, AK+SK, Passkey, etc.) are added: each engine is described to
// the dispatcher by `Named` at wiring time, and orchestration is the
// `Multi` decorator's responsibility.
type Authenticator interface {
	Authenticate(ctx context.Context) (context.Context, error)
}

// Option configures the Server middleware.
type Option func(*serverConfig)

type serverConfig struct {
	rules        map[string]*authnpb.AuthnRule
	errorHandler func(ctx context.Context, err error) error
	auditor      audit.Auditor
}

// WithRulesFuncs registers one or more rule-table generator functions.
// `protoc-gen-servora-authn` emits one
// `AuthnRules() map[string]*authnpb.AuthnRule` per .proto package; business
// code passes them as variadic args to merge across modules. Nil entries are
// skipped so business code can pass optional generators conditionally.
//
// Merge semantics:
//   - rule entries from later generators overwrite earlier ones.
//   - RPC paths use proto fully-qualified service names, so package-local
//     same-named services do not collide.
func WithRulesFuncs(fns ...func() map[string]*authnpb.AuthnRule) Option {
	return func(c *serverConfig) {
		for _, fn := range fns {
			if fn == nil {
				continue
			}
			rules := fn()
			if len(rules) == 0 {
				continue
			}
			if c.rules == nil {
				c.rules = make(map[string]*authnpb.AuthnRule, len(rules))
			}
			for op, rule := range rules {
				if rule == nil {
					continue
				}
				c.rules[op] = rule
			}
		}
	}
}

// WithErrorHandler installs a custom error transformer invoked when
// authentication fails. If the underlying error implements
// `SchemeAttemptsErr` (i.e. came from `Multi`), the hook can type-assert
// to retrieve per-scheme attempts.
func WithErrorHandler(h func(ctx context.Context, err error) error) Option {
	return func(c *serverConfig) { c.errorHandler = h }
}

// Server returns a Kratos middleware that dispatches authentication to the
// supplied `Authenticator` (typically a `Multi` decorator).
//
// Per-request behavior:
//
//  1. Resolve operation: `transport.FromServerContext(ctx).Operation()`.
//  2. MODE_PUBLIC passthrough: if the rule says public, do not call the engine.
//  3. MODE_REQUIRED installs the rule's scheme set into ctx. Empty schemes
//     intentionally install nil, so Multi tries every registered engine.
//     Missing or MODE_UNSPECIFIED rules also install nil.
//  4. Call `a.Authenticate(ctx)`.
//  5. Success → use the returned enriched ctx directly, call the handler.
//  6. Failure → optionally emit audit event, then either invoke
//     `WithErrorHandler` (if set) or return
//     `errors.Unauthorized("AUTHN_FAILED", reason)`.
func Server(a Authenticator, opts ...Option) middleware.Middleware {
	cfg := &serverConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			// Step 1: resolve operation (best-effort — may be absent in
			// non-server contexts; dispatch still proceeds with empty op,
			// which means rule lookup misses and the engine receives full
			// fail-open semantics).
			var op string
			if tr, ok := transport.FromServerContext(ctx); ok && tr != nil {
				op = tr.Operation()
			}

			// Step 2: MODE_PUBLIC passthrough — engine NOT called.
			// Business handler sees ctx as-is and is expected to treat
			// it as anonymous.
			rule := cfg.rules[op]
			if rule.GetMode() == authnpb.AuthnRule_MODE_PUBLIC {
				return handler(ctx, req)
			}

			// Step 3: build the allowed-schemes set for Multi to filter on.
			// Absent op → allowed=nil → Multi tries every engine.
			var allowed map[string]struct{}
			if rule.GetMode() == authnpb.AuthnRule_MODE_REQUIRED {
				allowed = stringSet(rule.GetSchemes())
			}

			// Step 4: install allowedSchemes before dispatch. `Multi`
			// reads it to filter engines.
			ctx = withAllowedSchemes(ctx, allowed)

			// Step 5: dispatch.
			enrichedCtx, err := a.Authenticate(ctx)

			// Step 6: failure path.
			if err != nil {
				reason := err.Error()
				if as, ok := err.(SchemeAttemptsErr); ok {
					reason = renderSchemeAttempts(as.SchemeAttempts())
				}
				// Emit audit event if auditor is configured.
				emitAuthnFailure(ctx, cfg.auditor, reason)
				if cfg.errorHandler != nil {
					return nil, cfg.errorHandler(ctx, err)
				}
				return nil, errors.Unauthorized(authnFailedReason, reason)
			}

			// Step 5: success path — use the enriched ctx from engine.
			scheme, _ := AuthTypeFrom(enrichedCtx)
			emitAuthnSuccess(enrichedCtx, cfg.auditor, scheme)
			return handler(enrichedCtx, req)
		}
	}
}

// authnFailedReason is the kratos error reason used for the default
// `errors.Unauthorized(...)` return when no `WithErrorHandler` is set.
const authnFailedReason = "AUTHN_FAILED"

// renderSchemeAttempts serializes a `[]SchemeAttempt` into the
// "scheme1: reason1; scheme2: reason2" form used in failure responses.
func renderSchemeAttempts(attempts []SchemeAttempt) string {
	if len(attempts) == 0 {
		return ""
	}
	parts := make([]string, 0, len(attempts))
	for _, at := range attempts {
		parts = append(parts, fmt.Sprintf("%s: %s", at.Scheme, at.Reason))
	}
	return strings.Join(parts, "; ")
}

// stringSet builds a set view of a string slice. Returns nil for empty
// input so callers can use `allowed == nil` to mean "no restriction".
func stringSet(xs []string) map[string]struct{} {
	if len(xs) == 0 {
		return nil
	}
	s := make(map[string]struct{}, len(xs))
	for _, x := range xs {
		s[x] = struct{}{}
	}
	return s
}
