// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContractRowsColumns holds the columns for the "contract_rows" table.
	ContractRowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true},
		{Name: "purge_time", Type: field.TypeTime, Nullable: true},
		{Name: "text_value", Type: field.TypeString, Default: ""},
		{Name: "unique_text", Type: field.TypeString},
		{Name: "numeric_value", Type: field.TypeInt32},
		{Name: "nullable_text", Type: field.TypeString, Nullable: true},
		{Name: "timestamp_value", Type: field.TypeTime},
		{Name: "updated_timestamp", Type: field.TypeTime},
		{Name: "duration_value", Type: field.TypeInt64, Default: 0},
		{Name: "enum_number", Type: field.TypeInt32, Default: 0},
	}
	// ContractRowsTable holds the schema information for the "contract_rows" table.
	ContractRowsTable = &schema.Table{
		Name:       "contract_rows",
		Columns:    ContractRowsColumns,
		PrimaryKey: []*schema.Column{ContractRowsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "contractrow_delete_time",
				Unique:  false,
				Columns: []*schema.Column{ContractRowsColumns[1]},
			},
			{
				Name:    "contractrow_purge_time",
				Unique:  false,
				Columns: []*schema.Column{ContractRowsColumns[3]},
			},
			{
				Name:    "contractrow_unique_text",
				Unique:  true,
				Columns: []*schema.Column{ContractRowsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContractRowsTable,
	}
)

func init() {
}
