// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionapi"
	"github.com/google/uuid"
)

// RbacPermissionApiQuery is the builder for querying RbacPermissionApi entities.
type RbacPermissionApiQuery struct {
	config
	ctx            *QueryContext
	order          []rbacpermissionapi.OrderOption
	inters         []Interceptor
	predicates     []predicate.RbacPermissionApi
	withPermission *RbacPermissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RbacPermissionApiQuery builder.
func (_q *RbacPermissionApiQuery) Where(ps ...predicate.RbacPermissionApi) *RbacPermissionApiQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RbacPermissionApiQuery) Limit(limit int) *RbacPermissionApiQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RbacPermissionApiQuery) Offset(offset int) *RbacPermissionApiQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RbacPermissionApiQuery) Unique(unique bool) *RbacPermissionApiQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RbacPermissionApiQuery) Order(o ...rbacpermissionapi.OrderOption) *RbacPermissionApiQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPermission chains the current query on the "permission" edge.
func (_q *RbacPermissionApiQuery) QueryPermission() *RbacPermissionQuery {
	query := (&RbacPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rbacpermissionapi.Table, rbacpermissionapi.FieldID, selector),
			sqlgraph.To(rbacpermission.Table, rbacpermission.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rbacpermissionapi.PermissionTable, rbacpermissionapi.PermissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RbacPermissionApi entity from the query.
// Returns a *NotFoundError when no RbacPermissionApi was found.
func (_q *RbacPermissionApiQuery) First(ctx context.Context) (*RbacPermissionApi, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rbacpermissionapi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) FirstX(ctx context.Context) *RbacPermissionApi {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RbacPermissionApi ID from the query.
// Returns a *NotFoundError when no RbacPermissionApi ID was found.
func (_q *RbacPermissionApiQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rbacpermissionapi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RbacPermissionApi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RbacPermissionApi entity is found.
// Returns a *NotFoundError when no RbacPermissionApi entities are found.
func (_q *RbacPermissionApiQuery) Only(ctx context.Context) (*RbacPermissionApi, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rbacpermissionapi.Label}
	default:
		return nil, &NotSingularError{rbacpermissionapi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) OnlyX(ctx context.Context) *RbacPermissionApi {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RbacPermissionApi ID in the query.
// Returns a *NotSingularError when more than one RbacPermissionApi ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RbacPermissionApiQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rbacpermissionapi.Label}
	default:
		err = &NotSingularError{rbacpermissionapi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RbacPermissionApis.
func (_q *RbacPermissionApiQuery) All(ctx context.Context) ([]*RbacPermissionApi, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RbacPermissionApi, *RbacPermissionApiQuery]()
	return withInterceptors[[]*RbacPermissionApi](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) AllX(ctx context.Context) []*RbacPermissionApi {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RbacPermissionApi IDs.
func (_q *RbacPermissionApiQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rbacpermissionapi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RbacPermissionApiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RbacPermissionApiQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RbacPermissionApiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RbacPermissionApiQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RbacPermissionApiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RbacPermissionApiQuery) Clone() *RbacPermissionApiQuery {
	if _q == nil {
		return nil
	}
	return &RbacPermissionApiQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]rbacpermissionapi.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.RbacPermissionApi{}, _q.predicates...),
		withPermission: _q.withPermission.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPermission tells the query-builder to eager-load the nodes that are connected to
// the "permission" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RbacPermissionApiQuery) WithPermission(opts ...func(*RbacPermissionQuery)) *RbacPermissionApiQuery {
	query := (&RbacPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPermission = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PermissionID uuid.UUID `json:"permission_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RbacPermissionApi.Query().
//		GroupBy(rbacpermissionapi.FieldPermissionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RbacPermissionApiQuery) GroupBy(field string, fields ...string) *RbacPermissionApiGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RbacPermissionApiGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rbacpermissionapi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PermissionID uuid.UUID `json:"permission_id,omitempty"`
//	}
//
//	client.RbacPermissionApi.Query().
//		Select(rbacpermissionapi.FieldPermissionID).
//		Scan(ctx, &v)
func (_q *RbacPermissionApiQuery) Select(fields ...string) *RbacPermissionApiSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RbacPermissionApiSelect{RbacPermissionApiQuery: _q}
	sbuild.label = rbacpermissionapi.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RbacPermissionApiSelect configured with the given aggregations.
func (_q *RbacPermissionApiQuery) Aggregate(fns ...AggregateFunc) *RbacPermissionApiSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RbacPermissionApiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rbacpermissionapi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RbacPermissionApiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RbacPermissionApi, error) {
	var (
		nodes       = []*RbacPermissionApi{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPermission != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RbacPermissionApi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RbacPermissionApi{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPermission; query != nil {
		if err := _q.loadPermission(ctx, query, nodes, nil,
			func(n *RbacPermissionApi, e *RbacPermission) { n.Edges.Permission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RbacPermissionApiQuery) loadPermission(ctx context.Context, query *RbacPermissionQuery, nodes []*RbacPermissionApi, init func(*RbacPermissionApi), assign func(*RbacPermissionApi, *RbacPermission)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*RbacPermissionApi)
	for i := range nodes {
		fk := nodes[i].PermissionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rbacpermission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "permission_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RbacPermissionApiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RbacPermissionApiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rbacpermissionapi.Table, rbacpermissionapi.Columns, sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissionapi.FieldID)
		for i := range fields {
			if fields[i] != rbacpermissionapi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPermission != nil {
			_spec.Node.AddColumnOnce(rbacpermissionapi.FieldPermissionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RbacPermissionApiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rbacpermissionapi.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rbacpermissionapi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RbacPermissionApiGroupBy is the group-by builder for RbacPermissionApi entities.
type RbacPermissionApiGroupBy struct {
	selector
	build *RbacPermissionApiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RbacPermissionApiGroupBy) Aggregate(fns ...AggregateFunc) *RbacPermissionApiGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RbacPermissionApiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RbacPermissionApiQuery, *RbacPermissionApiGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RbacPermissionApiGroupBy) sqlScan(ctx context.Context, root *RbacPermissionApiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RbacPermissionApiSelect is the builder for selecting fields of RbacPermissionApi entities.
type RbacPermissionApiSelect struct {
	*RbacPermissionApiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RbacPermissionApiSelect) Aggregate(fns ...AggregateFunc) *RbacPermissionApiSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RbacPermissionApiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RbacPermissionApiQuery, *RbacPermissionApiSelect](ctx, _s.RbacPermissionApiQuery, _s, _s.inters, v)
}

func (_s *RbacPermissionApiSelect) sqlScan(ctx context.Context, root *RbacPermissionApiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
