// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissiongroup"
	"github.com/google/uuid"
)

// RbacPermissionGroupUpdate is the builder for updating RbacPermissionGroup entities.
type RbacPermissionGroupUpdate struct {
	config
	hooks    []Hook
	mutation *RbacPermissionGroupMutation
}

// Where appends a list predicates to the RbacPermissionGroupUpdate builder.
func (_u *RbacPermissionGroupUpdate) Where(ps ...predicate.RbacPermissionGroup) *RbacPermissionGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RbacPermissionGroupUpdate) SetName(v string) *RbacPermissionGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdate) SetNillableName(v *string) *RbacPermissionGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetModule sets the "module" field.
func (_u *RbacPermissionGroupUpdate) SetModule(v string) *RbacPermissionGroupUpdate {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdate) SetNillableModule(v *string) *RbacPermissionGroupUpdate {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// ClearModule clears the value of the "module" field.
func (_u *RbacPermissionGroupUpdate) ClearModule() *RbacPermissionGroupUpdate {
	_u.mutation.ClearModule()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *RbacPermissionGroupUpdate) SetParentID(v uuid.UUID) *RbacPermissionGroupUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdate) SetNillableParentID(v *uuid.UUID) *RbacPermissionGroupUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *RbacPermissionGroupUpdate) ClearParentID() *RbacPermissionGroupUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetSort sets the "sort" field.
func (_u *RbacPermissionGroupUpdate) SetSort(v int) *RbacPermissionGroupUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdate) SetNillableSort(v *int) *RbacPermissionGroupUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *RbacPermissionGroupUpdate) AddSort(v int) *RbacPermissionGroupUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionGroupUpdate) SetUpdatedAt(v time.Time) *RbacPermissionGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the RbacPermission entity by IDs.
func (_u *RbacPermissionGroupUpdate) AddPermissionIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the RbacPermission entity.
func (_u *RbacPermissionGroupUpdate) AddPermissions(v ...*RbacPermission) *RbacPermissionGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// SetParent sets the "parent" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdate) SetParent(v *RbacPermissionGroup) *RbacPermissionGroupUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the RbacPermissionGroup entity by IDs.
func (_u *RbacPermissionGroupUpdate) AddChildIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdate) AddChildren(v ...*RbacPermissionGroup) *RbacPermissionGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the RbacPermissionGroupMutation object of the builder.
func (_u *RbacPermissionGroupUpdate) Mutation() *RbacPermissionGroupMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the RbacPermission entity.
func (_u *RbacPermissionGroupUpdate) ClearPermissions() *RbacPermissionGroupUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to RbacPermission entities by IDs.
func (_u *RbacPermissionGroupUpdate) RemovePermissionIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to RbacPermission entities.
func (_u *RbacPermissionGroupUpdate) RemovePermissions(v ...*RbacPermission) *RbacPermissionGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearParent clears the "parent" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdate) ClearParent() *RbacPermissionGroupUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdate) ClearChildren() *RbacPermissionGroupUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to RbacPermissionGroup entities by IDs.
func (_u *RbacPermissionGroupUpdate) RemoveChildIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to RbacPermissionGroup entities.
func (_u *RbacPermissionGroupUpdate) RemoveChildren(v ...*RbacPermissionGroup) *RbacPermissionGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacPermissionGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacPermissionGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermissiongroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacpermissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Module(); ok {
		if err := rbacpermissiongroup.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionGroup.module": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacPermissionGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissiongroup.Table, rbacpermissiongroup.Columns, sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacpermissiongroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(rbacpermissiongroup.FieldModule, field.TypeString, value)
	}
	if _u.mutation.ModuleCleared() {
		_spec.ClearField(rbacpermissiongroup.FieldModule, field.TypeString)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(rbacpermissiongroup.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(rbacpermissiongroup.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissiongroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissiongroup.ParentTable,
			Columns: []string{rbacpermissiongroup.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissiongroup.ParentTable,
			Columns: []string{rbacpermissiongroup.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacPermissionGroupUpdateOne is the builder for updating a single RbacPermissionGroup entity.
type RbacPermissionGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacPermissionGroupMutation
}

// SetName sets the "name" field.
func (_u *RbacPermissionGroupUpdateOne) SetName(v string) *RbacPermissionGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdateOne) SetNillableName(v *string) *RbacPermissionGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetModule sets the "module" field.
func (_u *RbacPermissionGroupUpdateOne) SetModule(v string) *RbacPermissionGroupUpdateOne {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdateOne) SetNillableModule(v *string) *RbacPermissionGroupUpdateOne {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// ClearModule clears the value of the "module" field.
func (_u *RbacPermissionGroupUpdateOne) ClearModule() *RbacPermissionGroupUpdateOne {
	_u.mutation.ClearModule()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *RbacPermissionGroupUpdateOne) SetParentID(v uuid.UUID) *RbacPermissionGroupUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdateOne) SetNillableParentID(v *uuid.UUID) *RbacPermissionGroupUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *RbacPermissionGroupUpdateOne) ClearParentID() *RbacPermissionGroupUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetSort sets the "sort" field.
func (_u *RbacPermissionGroupUpdateOne) SetSort(v int) *RbacPermissionGroupUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *RbacPermissionGroupUpdateOne) SetNillableSort(v *int) *RbacPermissionGroupUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *RbacPermissionGroupUpdateOne) AddSort(v int) *RbacPermissionGroupUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionGroupUpdateOne) SetUpdatedAt(v time.Time) *RbacPermissionGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the RbacPermission entity by IDs.
func (_u *RbacPermissionGroupUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the RbacPermission entity.
func (_u *RbacPermissionGroupUpdateOne) AddPermissions(v ...*RbacPermission) *RbacPermissionGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// SetParent sets the "parent" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdateOne) SetParent(v *RbacPermissionGroup) *RbacPermissionGroupUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the RbacPermissionGroup entity by IDs.
func (_u *RbacPermissionGroupUpdateOne) AddChildIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdateOne) AddChildren(v ...*RbacPermissionGroup) *RbacPermissionGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the RbacPermissionGroupMutation object of the builder.
func (_u *RbacPermissionGroupUpdateOne) Mutation() *RbacPermissionGroupMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the RbacPermission entity.
func (_u *RbacPermissionGroupUpdateOne) ClearPermissions() *RbacPermissionGroupUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to RbacPermission entities by IDs.
func (_u *RbacPermissionGroupUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to RbacPermission entities.
func (_u *RbacPermissionGroupUpdateOne) RemovePermissions(v ...*RbacPermission) *RbacPermissionGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearParent clears the "parent" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdateOne) ClearParent() *RbacPermissionGroupUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdateOne) ClearChildren() *RbacPermissionGroupUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to RbacPermissionGroup entities by IDs.
func (_u *RbacPermissionGroupUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *RbacPermissionGroupUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to RbacPermissionGroup entities.
func (_u *RbacPermissionGroupUpdateOne) RemoveChildren(v ...*RbacPermissionGroup) *RbacPermissionGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the RbacPermissionGroupUpdate builder.
func (_u *RbacPermissionGroupUpdateOne) Where(ps ...predicate.RbacPermissionGroup) *RbacPermissionGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacPermissionGroupUpdateOne) Select(field string, fields ...string) *RbacPermissionGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacPermissionGroup entity.
func (_u *RbacPermissionGroupUpdateOne) Save(ctx context.Context) (*RbacPermissionGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionGroupUpdateOne) SaveX(ctx context.Context) *RbacPermissionGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacPermissionGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermissiongroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacpermissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Module(); ok {
		if err := rbacpermissiongroup.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionGroup.module": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacPermissionGroupUpdateOne) sqlSave(ctx context.Context) (_node *RbacPermissionGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissiongroup.Table, rbacpermissiongroup.Columns, sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacPermissionGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissiongroup.FieldID)
		for _, f := range fields {
			if !rbacpermissiongroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacpermissiongroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacpermissiongroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(rbacpermissiongroup.FieldModule, field.TypeString, value)
	}
	if _u.mutation.ModuleCleared() {
		_spec.ClearField(rbacpermissiongroup.FieldModule, field.TypeString)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(rbacpermissiongroup.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(rbacpermissiongroup.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermissiongroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.PermissionsTable,
			Columns: []string{rbacpermissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissiongroup.ParentTable,
			Columns: []string{rbacpermissiongroup.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissiongroup.ParentTable,
			Columns: []string{rbacpermissiongroup.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermissiongroup.ChildrenTable,
			Columns: []string{rbacpermissiongroup.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RbacPermissionGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
