// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrole"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrolepermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacuserrole"
	"github.com/google/uuid"
)

// RbacRoleUpdate is the builder for updating RbacRole entities.
type RbacRoleUpdate struct {
	config
	hooks    []Hook
	mutation *RbacRoleMutation
}

// Where appends a list predicates to the RbacRoleUpdate builder.
func (_u *RbacRoleUpdate) Where(ps ...predicate.RbacRole) *RbacRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *RbacRoleUpdate) SetCode(v string) *RbacRoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableCode(v *string) *RbacRoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RbacRoleUpdate) SetName(v string) *RbacRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableName(v *string) *RbacRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RbacRoleUpdate) SetDescription(v string) *RbacRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableDescription(v *string) *RbacRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RbacRoleUpdate) ClearDescription() *RbacRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetType sets the "type" field.
func (_u *RbacRoleUpdate) SetType(v rbacrole.Type) *RbacRoleUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableType(v *rbacrole.Type) *RbacRoleUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsProtected sets the "is_protected" field.
func (_u *RbacRoleUpdate) SetIsProtected(v bool) *RbacRoleUpdate {
	_u.mutation.SetIsProtected(v)
	return _u
}

// SetNillableIsProtected sets the "is_protected" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableIsProtected(v *bool) *RbacRoleUpdate {
	if v != nil {
		_u.SetIsProtected(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RbacRoleUpdate) SetStatus(v rbacrole.Status) *RbacRoleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableStatus(v *rbacrole.Status) *RbacRoleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RbacRoleUpdate) SetTenantID(v uuid.UUID) *RbacRoleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RbacRoleUpdate) SetNillableTenantID(v *uuid.UUID) *RbacRoleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *RbacRoleUpdate) ClearTenantID() *RbacRoleUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacRoleUpdate) SetUpdatedAt(v time.Time) *RbacRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RbacRolePermission entity by IDs.
func (_u *RbacRoleUpdate) AddRolePermissionIDs(ids ...uuid.UUID) *RbacRoleUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacRoleUpdate) AddRolePermissions(v ...*RbacRolePermission) *RbacRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the RbacUserRole entity by IDs.
func (_u *RbacRoleUpdate) AddUserRoleIDs(ids ...uuid.UUID) *RbacRoleUpdate {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the RbacUserRole entity.
func (_u *RbacRoleUpdate) AddUserRoles(v ...*RbacUserRole) *RbacRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// Mutation returns the RbacRoleMutation object of the builder.
func (_u *RbacRoleUpdate) Mutation() *RbacRoleMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacRoleUpdate) ClearRolePermissions() *RbacRoleUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RbacRolePermission entities by IDs.
func (_u *RbacRoleUpdate) RemoveRolePermissionIDs(ids ...uuid.UUID) *RbacRoleUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RbacRolePermission entities.
func (_u *RbacRoleUpdate) RemoveRolePermissions(v ...*RbacRolePermission) *RbacRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearUserRoles clears all "user_roles" edges to the RbacUserRole entity.
func (_u *RbacRoleUpdate) ClearUserRoles() *RbacRoleUpdate {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to RbacUserRole entities by IDs.
func (_u *RbacRoleUpdate) RemoveUserRoleIDs(ids ...uuid.UUID) *RbacRoleUpdate {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to RbacUserRole entities.
func (_u *RbacRoleUpdate) RemoveUserRoles(v ...*RbacUserRole) *RbacRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacRoleUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RbacRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RbacRole.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := rbacrole.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RbacRole.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RbacRole.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrole.Table, rbacrole.Columns, sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rbacrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(rbacrole.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsProtected(); ok {
		_spec.SetField(rbacrole.FieldIsProtected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(rbacrole.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(rbacrole.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacRoleUpdateOne is the builder for updating a single RbacRole entity.
type RbacRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacRoleMutation
}

// SetCode sets the "code" field.
func (_u *RbacRoleUpdateOne) SetCode(v string) *RbacRoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableCode(v *string) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RbacRoleUpdateOne) SetName(v string) *RbacRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableName(v *string) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RbacRoleUpdateOne) SetDescription(v string) *RbacRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableDescription(v *string) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RbacRoleUpdateOne) ClearDescription() *RbacRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetType sets the "type" field.
func (_u *RbacRoleUpdateOne) SetType(v rbacrole.Type) *RbacRoleUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableType(v *rbacrole.Type) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIsProtected sets the "is_protected" field.
func (_u *RbacRoleUpdateOne) SetIsProtected(v bool) *RbacRoleUpdateOne {
	_u.mutation.SetIsProtected(v)
	return _u
}

// SetNillableIsProtected sets the "is_protected" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableIsProtected(v *bool) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetIsProtected(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RbacRoleUpdateOne) SetStatus(v rbacrole.Status) *RbacRoleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableStatus(v *rbacrole.Status) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RbacRoleUpdateOne) SetTenantID(v uuid.UUID) *RbacRoleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RbacRoleUpdateOne) SetNillableTenantID(v *uuid.UUID) *RbacRoleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *RbacRoleUpdateOne) ClearTenantID() *RbacRoleUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacRoleUpdateOne) SetUpdatedAt(v time.Time) *RbacRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RbacRolePermission entity by IDs.
func (_u *RbacRoleUpdateOne) AddRolePermissionIDs(ids ...uuid.UUID) *RbacRoleUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacRoleUpdateOne) AddRolePermissions(v ...*RbacRolePermission) *RbacRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the RbacUserRole entity by IDs.
func (_u *RbacRoleUpdateOne) AddUserRoleIDs(ids ...uuid.UUID) *RbacRoleUpdateOne {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the RbacUserRole entity.
func (_u *RbacRoleUpdateOne) AddUserRoles(v ...*RbacUserRole) *RbacRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// Mutation returns the RbacRoleMutation object of the builder.
func (_u *RbacRoleUpdateOne) Mutation() *RbacRoleMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacRoleUpdateOne) ClearRolePermissions() *RbacRoleUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RbacRolePermission entities by IDs.
func (_u *RbacRoleUpdateOne) RemoveRolePermissionIDs(ids ...uuid.UUID) *RbacRoleUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RbacRolePermission entities.
func (_u *RbacRoleUpdateOne) RemoveRolePermissions(v ...*RbacRolePermission) *RbacRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearUserRoles clears all "user_roles" edges to the RbacUserRole entity.
func (_u *RbacRoleUpdateOne) ClearUserRoles() *RbacRoleUpdateOne {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to RbacUserRole entities by IDs.
func (_u *RbacRoleUpdateOne) RemoveUserRoleIDs(ids ...uuid.UUID) *RbacRoleUpdateOne {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to RbacUserRole entities.
func (_u *RbacRoleUpdateOne) RemoveUserRoles(v ...*RbacUserRole) *RbacRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// Where appends a list predicates to the RbacRoleUpdate builder.
func (_u *RbacRoleUpdateOne) Where(ps ...predicate.RbacRole) *RbacRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacRoleUpdateOne) Select(field string, fields ...string) *RbacRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacRole entity.
func (_u *RbacRoleUpdateOne) Save(ctx context.Context) (*RbacRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacRoleUpdateOne) SaveX(ctx context.Context) *RbacRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RbacRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RbacRole.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := rbacrole.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RbacRole.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RbacRole.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacRoleUpdateOne) sqlSave(ctx context.Context) (_node *RbacRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrole.Table, rbacrole.Columns, sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacrole.FieldID)
		for _, f := range fields {
			if !rbacrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rbacrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(rbacrole.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsProtected(); ok {
		_spec.SetField(rbacrole.FieldIsProtected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacrole.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(rbacrole.FieldTenantID, field.TypeUUID, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(rbacrole.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RbacRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
