// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionapi"
	"github.com/google/uuid"
)

// RbacPermissionApiUpdate is the builder for updating RbacPermissionApi entities.
type RbacPermissionApiUpdate struct {
	config
	hooks    []Hook
	mutation *RbacPermissionApiMutation
}

// Where appends a list predicates to the RbacPermissionApiUpdate builder.
func (_u *RbacPermissionApiUpdate) Where(ps ...predicate.RbacPermissionApi) *RbacPermissionApiUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *RbacPermissionApiUpdate) SetPermissionID(v uuid.UUID) *RbacPermissionApiUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RbacPermissionApiUpdate) SetNillablePermissionID(v *uuid.UUID) *RbacPermissionApiUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *RbacPermissionApiUpdate) SetAPIMethod(v string) *RbacPermissionApiUpdate {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *RbacPermissionApiUpdate) SetNillableAPIMethod(v *string) *RbacPermissionApiUpdate {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *RbacPermissionApiUpdate) SetAPIPath(v string) *RbacPermissionApiUpdate {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *RbacPermissionApiUpdate) SetNillableAPIPath(v *string) *RbacPermissionApiUpdate {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// SetPermission sets the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionApiUpdate) SetPermission(v *RbacPermission) *RbacPermissionApiUpdate {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the RbacPermissionApiMutation object of the builder.
func (_u *RbacPermissionApiUpdate) Mutation() *RbacPermissionApiMutation {
	return _u.mutation
}

// ClearPermission clears the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionApiUpdate) ClearPermission() *RbacPermissionApiUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacPermissionApiUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionApiUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacPermissionApiUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionApiUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionApiUpdate) check() error {
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := rbacpermissionapi.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionApi.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := rbacpermissionapi.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionApi.api_path": %w`, err)}
		}
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionApi.permission"`)
	}
	return nil
}

func (_u *RbacPermissionApiUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionapi.Table, rbacpermissionapi.Columns, sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(rbacpermissionapi.FieldAPIMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(rbacpermissionapi.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionapi.PermissionTable,
			Columns: []string{rbacpermissionapi.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionapi.PermissionTable,
			Columns: []string{rbacpermissionapi.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionapi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacPermissionApiUpdateOne is the builder for updating a single RbacPermissionApi entity.
type RbacPermissionApiUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacPermissionApiMutation
}

// SetPermissionID sets the "permission_id" field.
func (_u *RbacPermissionApiUpdateOne) SetPermissionID(v uuid.UUID) *RbacPermissionApiUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RbacPermissionApiUpdateOne) SetNillablePermissionID(v *uuid.UUID) *RbacPermissionApiUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetAPIMethod sets the "api_method" field.
func (_u *RbacPermissionApiUpdateOne) SetAPIMethod(v string) *RbacPermissionApiUpdateOne {
	_u.mutation.SetAPIMethod(v)
	return _u
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_u *RbacPermissionApiUpdateOne) SetNillableAPIMethod(v *string) *RbacPermissionApiUpdateOne {
	if v != nil {
		_u.SetAPIMethod(*v)
	}
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *RbacPermissionApiUpdateOne) SetAPIPath(v string) *RbacPermissionApiUpdateOne {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *RbacPermissionApiUpdateOne) SetNillableAPIPath(v *string) *RbacPermissionApiUpdateOne {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// SetPermission sets the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionApiUpdateOne) SetPermission(v *RbacPermission) *RbacPermissionApiUpdateOne {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the RbacPermissionApiMutation object of the builder.
func (_u *RbacPermissionApiUpdateOne) Mutation() *RbacPermissionApiMutation {
	return _u.mutation
}

// ClearPermission clears the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionApiUpdateOne) ClearPermission() *RbacPermissionApiUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// Where appends a list predicates to the RbacPermissionApiUpdate builder.
func (_u *RbacPermissionApiUpdateOne) Where(ps ...predicate.RbacPermissionApi) *RbacPermissionApiUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacPermissionApiUpdateOne) Select(field string, fields ...string) *RbacPermissionApiUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacPermissionApi entity.
func (_u *RbacPermissionApiUpdateOne) Save(ctx context.Context) (*RbacPermissionApi, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionApiUpdateOne) SaveX(ctx context.Context) *RbacPermissionApi {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacPermissionApiUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionApiUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionApiUpdateOne) check() error {
	if v, ok := _u.mutation.APIMethod(); ok {
		if err := rbacpermissionapi.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionApi.api_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPath(); ok {
		if err := rbacpermissionapi.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "RbacPermissionApi.api_path": %w`, err)}
		}
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionApi.permission"`)
	}
	return nil
}

func (_u *RbacPermissionApiUpdateOne) sqlSave(ctx context.Context) (_node *RbacPermissionApi, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionapi.Table, rbacpermissionapi.Columns, sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacPermissionApi.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissionapi.FieldID)
		for _, f := range fields {
			if !rbacpermissionapi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacpermissionapi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIMethod(); ok {
		_spec.SetField(rbacpermissionapi.FieldAPIMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(rbacpermissionapi.FieldAPIPath, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionapi.PermissionTable,
			Columns: []string{rbacpermissionapi.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionapi.PermissionTable,
			Columns: []string{rbacpermissionapi.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RbacPermissionApi{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionapi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
