// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionapi"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissiongroup"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionmenu"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrolepermission"
	"github.com/google/uuid"
)

// RbacPermissionUpdate is the builder for updating RbacPermission entities.
type RbacPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *RbacPermissionMutation
}

// Where appends a list predicates to the RbacPermissionUpdate builder.
func (_u *RbacPermissionUpdate) Where(ps ...predicate.RbacPermission) *RbacPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *RbacPermissionUpdate) SetCode(v string) *RbacPermissionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RbacPermissionUpdate) SetNillableCode(v *string) *RbacPermissionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RbacPermissionUpdate) SetName(v string) *RbacPermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacPermissionUpdate) SetNillableName(v *string) *RbacPermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RbacPermissionUpdate) SetDescription(v string) *RbacPermissionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RbacPermissionUpdate) SetNillableDescription(v *string) *RbacPermissionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RbacPermissionUpdate) ClearDescription() *RbacPermissionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RbacPermissionUpdate) SetGroupID(v uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RbacPermissionUpdate) SetNillableGroupID(v *uuid.UUID) *RbacPermissionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RbacPermissionUpdate) ClearGroupID() *RbacPermissionUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RbacPermissionUpdate) SetStatus(v rbacpermission.Status) *RbacPermissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RbacPermissionUpdate) SetNillableStatus(v *rbacpermission.Status) *RbacPermissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionUpdate) SetUpdatedAt(v time.Time) *RbacPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionUpdate) SetGroup(v *RbacPermissionGroup) *RbacPermissionUpdate {
	return _u.SetGroupID(v.ID)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RbacRolePermission entity by IDs.
func (_u *RbacPermissionUpdate) AddRolePermissionIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacPermissionUpdate) AddRolePermissions(v ...*RbacRolePermission) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddPermissionMenuIDs adds the "permission_menus" edge to the RbacPermissionMenu entity by IDs.
func (_u *RbacPermissionUpdate) AddPermissionMenuIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.AddPermissionMenuIDs(ids...)
	return _u
}

// AddPermissionMenus adds the "permission_menus" edges to the RbacPermissionMenu entity.
func (_u *RbacPermissionUpdate) AddPermissionMenus(v ...*RbacPermissionMenu) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionMenuIDs(ids...)
}

// AddPermissionAPIIDs adds the "permission_apis" edge to the RbacPermissionApi entity by IDs.
func (_u *RbacPermissionUpdate) AddPermissionAPIIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.AddPermissionAPIIDs(ids...)
	return _u
}

// AddPermissionApis adds the "permission_apis" edges to the RbacPermissionApi entity.
func (_u *RbacPermissionUpdate) AddPermissionApis(v ...*RbacPermissionApi) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionAPIIDs(ids...)
}

// Mutation returns the RbacPermissionMutation object of the builder.
func (_u *RbacPermissionUpdate) Mutation() *RbacPermissionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionUpdate) ClearGroup() *RbacPermissionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearRolePermissions clears all "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacPermissionUpdate) ClearRolePermissions() *RbacPermissionUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RbacRolePermission entities by IDs.
func (_u *RbacPermissionUpdate) RemoveRolePermissionIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RbacRolePermission entities.
func (_u *RbacPermissionUpdate) RemoveRolePermissions(v ...*RbacRolePermission) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearPermissionMenus clears all "permission_menus" edges to the RbacPermissionMenu entity.
func (_u *RbacPermissionUpdate) ClearPermissionMenus() *RbacPermissionUpdate {
	_u.mutation.ClearPermissionMenus()
	return _u
}

// RemovePermissionMenuIDs removes the "permission_menus" edge to RbacPermissionMenu entities by IDs.
func (_u *RbacPermissionUpdate) RemovePermissionMenuIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.RemovePermissionMenuIDs(ids...)
	return _u
}

// RemovePermissionMenus removes "permission_menus" edges to RbacPermissionMenu entities.
func (_u *RbacPermissionUpdate) RemovePermissionMenus(v ...*RbacPermissionMenu) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionMenuIDs(ids...)
}

// ClearPermissionApis clears all "permission_apis" edges to the RbacPermissionApi entity.
func (_u *RbacPermissionUpdate) ClearPermissionApis() *RbacPermissionUpdate {
	_u.mutation.ClearPermissionApis()
	return _u
}

// RemovePermissionAPIIDs removes the "permission_apis" edge to RbacPermissionApi entities by IDs.
func (_u *RbacPermissionUpdate) RemovePermissionAPIIDs(ids ...uuid.UUID) *RbacPermissionUpdate {
	_u.mutation.RemovePermissionAPIIDs(ids...)
	return _u
}

// RemovePermissionApis removes "permission_apis" edges to RbacPermissionApi entities.
func (_u *RbacPermissionUpdate) RemovePermissionApis(v ...*RbacPermissionApi) *RbacPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionAPIIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacpermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacpermission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacpermission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermission.Table, rbacpermission.Columns, sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacpermission.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacpermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rbacpermission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacpermission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermission.GroupTable,
			Columns: []string{rbacpermission.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermission.GroupTable,
			Columns: []string{rbacpermission.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionMenusIDs(); len(nodes) > 0 && !_u.mutation.PermissionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionApisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionApisIDs(); len(nodes) > 0 && !_u.mutation.PermissionApisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionApisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacPermissionUpdateOne is the builder for updating a single RbacPermission entity.
type RbacPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacPermissionMutation
}

// SetCode sets the "code" field.
func (_u *RbacPermissionUpdateOne) SetCode(v string) *RbacPermissionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RbacPermissionUpdateOne) SetNillableCode(v *string) *RbacPermissionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RbacPermissionUpdateOne) SetName(v string) *RbacPermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RbacPermissionUpdateOne) SetNillableName(v *string) *RbacPermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RbacPermissionUpdateOne) SetDescription(v string) *RbacPermissionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RbacPermissionUpdateOne) SetNillableDescription(v *string) *RbacPermissionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RbacPermissionUpdateOne) ClearDescription() *RbacPermissionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RbacPermissionUpdateOne) SetGroupID(v uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RbacPermissionUpdateOne) SetNillableGroupID(v *uuid.UUID) *RbacPermissionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RbacPermissionUpdateOne) ClearGroupID() *RbacPermissionUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RbacPermissionUpdateOne) SetStatus(v rbacpermission.Status) *RbacPermissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RbacPermissionUpdateOne) SetNillableStatus(v *rbacpermission.Status) *RbacPermissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RbacPermissionUpdateOne) SetUpdatedAt(v time.Time) *RbacPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionUpdateOne) SetGroup(v *RbacPermissionGroup) *RbacPermissionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RbacRolePermission entity by IDs.
func (_u *RbacPermissionUpdateOne) AddRolePermissionIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacPermissionUpdateOne) AddRolePermissions(v ...*RbacRolePermission) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddPermissionMenuIDs adds the "permission_menus" edge to the RbacPermissionMenu entity by IDs.
func (_u *RbacPermissionUpdateOne) AddPermissionMenuIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.AddPermissionMenuIDs(ids...)
	return _u
}

// AddPermissionMenus adds the "permission_menus" edges to the RbacPermissionMenu entity.
func (_u *RbacPermissionUpdateOne) AddPermissionMenus(v ...*RbacPermissionMenu) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionMenuIDs(ids...)
}

// AddPermissionAPIIDs adds the "permission_apis" edge to the RbacPermissionApi entity by IDs.
func (_u *RbacPermissionUpdateOne) AddPermissionAPIIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.AddPermissionAPIIDs(ids...)
	return _u
}

// AddPermissionApis adds the "permission_apis" edges to the RbacPermissionApi entity.
func (_u *RbacPermissionUpdateOne) AddPermissionApis(v ...*RbacPermissionApi) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionAPIIDs(ids...)
}

// Mutation returns the RbacPermissionMutation object of the builder.
func (_u *RbacPermissionUpdateOne) Mutation() *RbacPermissionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the RbacPermissionGroup entity.
func (_u *RbacPermissionUpdateOne) ClearGroup() *RbacPermissionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearRolePermissions clears all "role_permissions" edges to the RbacRolePermission entity.
func (_u *RbacPermissionUpdateOne) ClearRolePermissions() *RbacPermissionUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RbacRolePermission entities by IDs.
func (_u *RbacPermissionUpdateOne) RemoveRolePermissionIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RbacRolePermission entities.
func (_u *RbacPermissionUpdateOne) RemoveRolePermissions(v ...*RbacRolePermission) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearPermissionMenus clears all "permission_menus" edges to the RbacPermissionMenu entity.
func (_u *RbacPermissionUpdateOne) ClearPermissionMenus() *RbacPermissionUpdateOne {
	_u.mutation.ClearPermissionMenus()
	return _u
}

// RemovePermissionMenuIDs removes the "permission_menus" edge to RbacPermissionMenu entities by IDs.
func (_u *RbacPermissionUpdateOne) RemovePermissionMenuIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.RemovePermissionMenuIDs(ids...)
	return _u
}

// RemovePermissionMenus removes "permission_menus" edges to RbacPermissionMenu entities.
func (_u *RbacPermissionUpdateOne) RemovePermissionMenus(v ...*RbacPermissionMenu) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionMenuIDs(ids...)
}

// ClearPermissionApis clears all "permission_apis" edges to the RbacPermissionApi entity.
func (_u *RbacPermissionUpdateOne) ClearPermissionApis() *RbacPermissionUpdateOne {
	_u.mutation.ClearPermissionApis()
	return _u
}

// RemovePermissionAPIIDs removes the "permission_apis" edge to RbacPermissionApi entities by IDs.
func (_u *RbacPermissionUpdateOne) RemovePermissionAPIIDs(ids ...uuid.UUID) *RbacPermissionUpdateOne {
	_u.mutation.RemovePermissionAPIIDs(ids...)
	return _u
}

// RemovePermissionApis removes "permission_apis" edges to RbacPermissionApi entities.
func (_u *RbacPermissionUpdateOne) RemovePermissionApis(v ...*RbacPermissionApi) *RbacPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionAPIIDs(ids...)
}

// Where appends a list predicates to the RbacPermissionUpdate builder.
func (_u *RbacPermissionUpdateOne) Where(ps ...predicate.RbacPermission) *RbacPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacPermissionUpdateOne) Select(field string, fields ...string) *RbacPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacPermission entity.
func (_u *RbacPermissionUpdateOne) Save(ctx context.Context) (*RbacPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionUpdateOne) SaveX(ctx context.Context) *RbacPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RbacPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacpermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacpermission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacpermission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RbacPermission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacPermissionUpdateOne) sqlSave(ctx context.Context) (_node *RbacPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermission.Table, rbacpermission.Columns, sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermission.FieldID)
		for _, f := range fields {
			if !rbacpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacpermission.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacpermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rbacpermission.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacpermission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermission.GroupTable,
			Columns: []string{rbacpermission.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermission.GroupTable,
			Columns: []string{rbacpermission.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.RolePermissionsTable,
			Columns: []string{rbacpermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionMenusIDs(); len(nodes) > 0 && !_u.mutation.PermissionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionMenusTable,
			Columns: []string{rbacpermission.PermissionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionApisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionApisIDs(); len(nodes) > 0 && !_u.mutation.PermissionApisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionApisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacpermission.PermissionApisTable,
			Columns: []string{rbacpermission.PermissionApisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermissionapi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RbacPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
