// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrole"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrolepermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacuserrole"
	"github.com/google/uuid"
)

// RbacRoleCreate is the builder for creating a RbacRole entity.
type RbacRoleCreate struct {
	config
	mutation *RbacRoleMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *RbacRoleCreate) SetCode(v string) *RbacRoleCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RbacRoleCreate) SetName(v string) *RbacRoleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RbacRoleCreate) SetDescription(v string) *RbacRoleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableDescription(v *string) *RbacRoleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *RbacRoleCreate) SetType(v rbacrole.Type) *RbacRoleCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableType(v *rbacrole.Type) *RbacRoleCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetIsProtected sets the "is_protected" field.
func (_c *RbacRoleCreate) SetIsProtected(v bool) *RbacRoleCreate {
	_c.mutation.SetIsProtected(v)
	return _c
}

// SetNillableIsProtected sets the "is_protected" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableIsProtected(v *bool) *RbacRoleCreate {
	if v != nil {
		_c.SetIsProtected(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RbacRoleCreate) SetStatus(v rbacrole.Status) *RbacRoleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableStatus(v *rbacrole.Status) *RbacRoleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RbacRoleCreate) SetTenantID(v uuid.UUID) *RbacRoleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableTenantID(v *uuid.UUID) *RbacRoleCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RbacRoleCreate) SetCreatedAt(v time.Time) *RbacRoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableCreatedAt(v *time.Time) *RbacRoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RbacRoleCreate) SetUpdatedAt(v time.Time) *RbacRoleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableUpdatedAt(v *time.Time) *RbacRoleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RbacRoleCreate) SetID(v uuid.UUID) *RbacRoleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RbacRoleCreate) SetNillableID(v *uuid.UUID) *RbacRoleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RbacRolePermission entity by IDs.
func (_c *RbacRoleCreate) AddRolePermissionIDs(ids ...uuid.UUID) *RbacRoleCreate {
	_c.mutation.AddRolePermissionIDs(ids...)
	return _c
}

// AddRolePermissions adds the "role_permissions" edges to the RbacRolePermission entity.
func (_c *RbacRoleCreate) AddRolePermissions(v ...*RbacRolePermission) *RbacRoleCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRolePermissionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the RbacUserRole entity by IDs.
func (_c *RbacRoleCreate) AddUserRoleIDs(ids ...uuid.UUID) *RbacRoleCreate {
	_c.mutation.AddUserRoleIDs(ids...)
	return _c
}

// AddUserRoles adds the "user_roles" edges to the RbacUserRole entity.
func (_c *RbacRoleCreate) AddUserRoles(v ...*RbacUserRole) *RbacRoleCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserRoleIDs(ids...)
}

// Mutation returns the RbacRoleMutation object of the builder.
func (_c *RbacRoleCreate) Mutation() *RbacRoleMutation {
	return _c.mutation
}

// Save creates the RbacRole in the database.
func (_c *RbacRoleCreate) Save(ctx context.Context) (*RbacRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacRoleCreate) SaveX(ctx context.Context) *RbacRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacRoleCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := rbacrole.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.IsProtected(); !ok {
		v := rbacrole.DefaultIsProtected
		_c.mutation.SetIsProtected(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rbacrole.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rbacrole.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rbacrole.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := rbacrole.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacRoleCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "RbacRole.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := rbacrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RbacRole.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RbacRole.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := rbacrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RbacRole.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := rbacrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RbacRole.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RbacRole.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := rbacrole.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RbacRole.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsProtected(); !ok {
		return &ValidationError{Name: "is_protected", err: errors.New(`ent: missing required field "RbacRole.is_protected"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RbacRole.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rbacrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RbacRole.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RbacRole.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RbacRole.updated_at"`)}
	}
	return nil
}

func (_c *RbacRoleCreate) sqlSave(ctx context.Context) (*RbacRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacRoleCreate) createSpec() (*RbacRole, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacrole.Table, sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(rbacrole.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rbacrole.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rbacrole.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(rbacrole.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.IsProtected(); ok {
		_spec.SetField(rbacrole.FieldIsProtected, field.TypeBool, value)
		_node.IsProtected = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rbacrole.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(rbacrole.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rbacrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrole.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RbacRoleCreateBulk is the builder for creating many RbacRole entities in bulk.
type RbacRoleCreateBulk struct {
	config
	err      error
	builders []*RbacRoleCreate
}

// Save creates the RbacRole entities in the database.
func (_c *RbacRoleCreateBulk) Save(ctx context.Context) ([]*RbacRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacRoleCreateBulk) SaveX(ctx context.Context) []*RbacRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
