// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissiongroup"
	"github.com/google/uuid"
)

// RbacPermissionGroup is the model entity for the RbacPermissionGroup schema.
type RbacPermissionGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Module holds the value of the "module" field.
	Module *string `json:"module,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RbacPermissionGroupQuery when eager-loading is set.
	Edges        RbacPermissionGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RbacPermissionGroupEdges holds the relations/edges for other nodes in the graph.
type RbacPermissionGroupEdges struct {
	// Permissions holds the value of the permissions edge.
	Permissions []*RbacPermission `json:"permissions,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *RbacPermissionGroup `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*RbacPermissionGroup `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e RbacPermissionGroupEdges) PermissionsOrErr() ([]*RbacPermission, error) {
	if e.loadedTypes[0] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacPermissionGroupEdges) ParentOrErr() (*RbacPermissionGroup, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: rbacpermissiongroup.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e RbacPermissionGroupEdges) ChildrenOrErr() ([]*RbacPermissionGroup, error) {
	if e.loadedTypes[2] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacPermissionGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacpermissiongroup.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rbacpermissiongroup.FieldSort:
			values[i] = new(sql.NullInt64)
		case rbacpermissiongroup.FieldName, rbacpermissiongroup.FieldModule:
			values[i] = new(sql.NullString)
		case rbacpermissiongroup.FieldCreatedAt, rbacpermissiongroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case rbacpermissiongroup.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacPermissionGroup fields.
func (_m *RbacPermissionGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacpermissiongroup.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rbacpermissiongroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case rbacpermissiongroup.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = new(string)
				*_m.Module = value.String
			}
		case rbacpermissiongroup.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uuid.UUID)
				*_m.ParentID = *value.S.(*uuid.UUID)
			}
		case rbacpermissiongroup.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case rbacpermissiongroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rbacpermissiongroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacPermissionGroup.
// This includes values selected through modifiers, order, etc.
func (_m *RbacPermissionGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermissions queries the "permissions" edge of the RbacPermissionGroup entity.
func (_m *RbacPermissionGroup) QueryPermissions() *RbacPermissionQuery {
	return NewRbacPermissionGroupClient(_m.config).QueryPermissions(_m)
}

// QueryParent queries the "parent" edge of the RbacPermissionGroup entity.
func (_m *RbacPermissionGroup) QueryParent() *RbacPermissionGroupQuery {
	return NewRbacPermissionGroupClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the RbacPermissionGroup entity.
func (_m *RbacPermissionGroup) QueryChildren() *RbacPermissionGroupQuery {
	return NewRbacPermissionGroupClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this RbacPermissionGroup.
// Note that you need to call RbacPermissionGroup.Unwrap() before calling this method if this RbacPermissionGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacPermissionGroup) Update() *RbacPermissionGroupUpdateOne {
	return NewRbacPermissionGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacPermissionGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacPermissionGroup) Unwrap() *RbacPermissionGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacPermissionGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacPermissionGroup) String() string {
	var builder strings.Builder
	builder.WriteString("RbacPermissionGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Module; v != nil {
		builder.WriteString("module=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RbacPermissionGroups is a parsable slice of RbacPermissionGroup.
type RbacPermissionGroups []*RbacPermissionGroup
