// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrole"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacrolepermission"
	"github.com/google/uuid"
)

// RbacRolePermissionCreate is the builder for creating a RbacRolePermission entity.
type RbacRolePermissionCreate struct {
	config
	mutation *RbacRolePermissionMutation
	hooks    []Hook
}

// SetRoleID sets the "role_id" field.
func (_c *RbacRolePermissionCreate) SetRoleID(v uuid.UUID) *RbacRolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *RbacRolePermissionCreate) SetPermissionID(v uuid.UUID) *RbacRolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetEffect sets the "effect" field.
func (_c *RbacRolePermissionCreate) SetEffect(v rbacrolepermission.Effect) *RbacRolePermissionCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillableEffect(v *rbacrolepermission.Effect) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetEffect(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RbacRolePermissionCreate) SetPriority(v int) *RbacRolePermissionCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillablePriority(v *int) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RbacRolePermissionCreate) SetTenantID(v uuid.UUID) *RbacRolePermissionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillableTenantID(v *uuid.UUID) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RbacRolePermissionCreate) SetCreatedAt(v time.Time) *RbacRolePermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillableCreatedAt(v *time.Time) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RbacRolePermissionCreate) SetUpdatedAt(v time.Time) *RbacRolePermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillableUpdatedAt(v *time.Time) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RbacRolePermissionCreate) SetID(v uuid.UUID) *RbacRolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RbacRolePermissionCreate) SetNillableID(v *uuid.UUID) *RbacRolePermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRole sets the "role" edge to the RbacRole entity.
func (_c *RbacRolePermissionCreate) SetRole(v *RbacRole) *RbacRolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the RbacPermission entity.
func (_c *RbacRolePermissionCreate) SetPermission(v *RbacPermission) *RbacRolePermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// Mutation returns the RbacRolePermissionMutation object of the builder.
func (_c *RbacRolePermissionCreate) Mutation() *RbacRolePermissionMutation {
	return _c.mutation
}

// Save creates the RbacRolePermission in the database.
func (_c *RbacRolePermissionCreate) Save(ctx context.Context) (*RbacRolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacRolePermissionCreate) SaveX(ctx context.Context) *RbacRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacRolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacRolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacRolePermissionCreate) defaults() {
	if _, ok := _c.mutation.Effect(); !ok {
		v := rbacrolepermission.DefaultEffect
		_c.mutation.SetEffect(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := rbacrolepermission.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rbacrolepermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rbacrolepermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := rbacrolepermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacRolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "RbacRolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "RbacRolePermission.permission_id"`)}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "RbacRolePermission.effect"`)}
	}
	if v, ok := _c.mutation.Effect(); ok {
		if err := rbacrolepermission.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "RbacRolePermission.effect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RbacRolePermission.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RbacRolePermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RbacRolePermission.updated_at"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "RbacRolePermission.role"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "RbacRolePermission.permission"`)}
	}
	return nil
}

func (_c *RbacRolePermissionCreate) sqlSave(ctx context.Context) (*RbacRolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacRolePermissionCreate) createSpec() (*RbacRolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacRolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacrolepermission.Table, sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(rbacrolepermission.FieldEffect, field.TypeEnum, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(rbacrolepermission.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(rbacrolepermission.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rbacrolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrolepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.RoleTable,
			Columns: []string{rbacrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.PermissionTable,
			Columns: []string{rbacrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RbacRolePermissionCreateBulk is the builder for creating many RbacRolePermission entities in bulk.
type RbacRolePermissionCreateBulk struct {
	config
	err      error
	builders []*RbacRolePermissionCreate
}

// Save creates the RbacRolePermission entities in the database.
func (_c *RbacRolePermissionCreateBulk) Save(ctx context.Context) ([]*RbacRolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacRolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacRolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacRolePermissionCreateBulk) SaveX(ctx context.Context) []*RbacRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacRolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacRolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
