// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissiongroup"
	"github.com/google/uuid"
)

// RbacPermissionGroupQuery is the builder for querying RbacPermissionGroup entities.
type RbacPermissionGroupQuery struct {
	config
	ctx             *QueryContext
	order           []rbacpermissiongroup.OrderOption
	inters          []Interceptor
	predicates      []predicate.RbacPermissionGroup
	withPermissions *RbacPermissionQuery
	withParent      *RbacPermissionGroupQuery
	withChildren    *RbacPermissionGroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RbacPermissionGroupQuery builder.
func (_q *RbacPermissionGroupQuery) Where(ps ...predicate.RbacPermissionGroup) *RbacPermissionGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RbacPermissionGroupQuery) Limit(limit int) *RbacPermissionGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RbacPermissionGroupQuery) Offset(offset int) *RbacPermissionGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RbacPermissionGroupQuery) Unique(unique bool) *RbacPermissionGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RbacPermissionGroupQuery) Order(o ...rbacpermissiongroup.OrderOption) *RbacPermissionGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPermissions chains the current query on the "permissions" edge.
func (_q *RbacPermissionGroupQuery) QueryPermissions() *RbacPermissionQuery {
	query := (&RbacPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rbacpermissiongroup.Table, rbacpermissiongroup.FieldID, selector),
			sqlgraph.To(rbacpermission.Table, rbacpermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rbacpermissiongroup.PermissionsTable, rbacpermissiongroup.PermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *RbacPermissionGroupQuery) QueryParent() *RbacPermissionGroupQuery {
	query := (&RbacPermissionGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rbacpermissiongroup.Table, rbacpermissiongroup.FieldID, selector),
			sqlgraph.To(rbacpermissiongroup.Table, rbacpermissiongroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rbacpermissiongroup.ParentTable, rbacpermissiongroup.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (_q *RbacPermissionGroupQuery) QueryChildren() *RbacPermissionGroupQuery {
	query := (&RbacPermissionGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rbacpermissiongroup.Table, rbacpermissiongroup.FieldID, selector),
			sqlgraph.To(rbacpermissiongroup.Table, rbacpermissiongroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rbacpermissiongroup.ChildrenTable, rbacpermissiongroup.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RbacPermissionGroup entity from the query.
// Returns a *NotFoundError when no RbacPermissionGroup was found.
func (_q *RbacPermissionGroupQuery) First(ctx context.Context) (*RbacPermissionGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rbacpermissiongroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) FirstX(ctx context.Context) *RbacPermissionGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RbacPermissionGroup ID from the query.
// Returns a *NotFoundError when no RbacPermissionGroup ID was found.
func (_q *RbacPermissionGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rbacpermissiongroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RbacPermissionGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RbacPermissionGroup entity is found.
// Returns a *NotFoundError when no RbacPermissionGroup entities are found.
func (_q *RbacPermissionGroupQuery) Only(ctx context.Context) (*RbacPermissionGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rbacpermissiongroup.Label}
	default:
		return nil, &NotSingularError{rbacpermissiongroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) OnlyX(ctx context.Context) *RbacPermissionGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RbacPermissionGroup ID in the query.
// Returns a *NotSingularError when more than one RbacPermissionGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RbacPermissionGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rbacpermissiongroup.Label}
	default:
		err = &NotSingularError{rbacpermissiongroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RbacPermissionGroups.
func (_q *RbacPermissionGroupQuery) All(ctx context.Context) ([]*RbacPermissionGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RbacPermissionGroup, *RbacPermissionGroupQuery]()
	return withInterceptors[[]*RbacPermissionGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) AllX(ctx context.Context) []*RbacPermissionGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RbacPermissionGroup IDs.
func (_q *RbacPermissionGroupQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rbacpermissiongroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RbacPermissionGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RbacPermissionGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RbacPermissionGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RbacPermissionGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RbacPermissionGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RbacPermissionGroupQuery) Clone() *RbacPermissionGroupQuery {
	if _q == nil {
		return nil
	}
	return &RbacPermissionGroupQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]rbacpermissiongroup.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.RbacPermissionGroup{}, _q.predicates...),
		withPermissions: _q.withPermissions.Clone(),
		withParent:      _q.withParent.Clone(),
		withChildren:    _q.withChildren.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPermissions tells the query-builder to eager-load the nodes that are connected to
// the "permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RbacPermissionGroupQuery) WithPermissions(opts ...func(*RbacPermissionQuery)) *RbacPermissionGroupQuery {
	query := (&RbacPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPermissions = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RbacPermissionGroupQuery) WithParent(opts ...func(*RbacPermissionGroupQuery)) *RbacPermissionGroupQuery {
	query := (&RbacPermissionGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RbacPermissionGroupQuery) WithChildren(opts ...func(*RbacPermissionGroupQuery)) *RbacPermissionGroupQuery {
	query := (&RbacPermissionGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RbacPermissionGroup.Query().
//		GroupBy(rbacpermissiongroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RbacPermissionGroupQuery) GroupBy(field string, fields ...string) *RbacPermissionGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RbacPermissionGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rbacpermissiongroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RbacPermissionGroup.Query().
//		Select(rbacpermissiongroup.FieldName).
//		Scan(ctx, &v)
func (_q *RbacPermissionGroupQuery) Select(fields ...string) *RbacPermissionGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RbacPermissionGroupSelect{RbacPermissionGroupQuery: _q}
	sbuild.label = rbacpermissiongroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RbacPermissionGroupSelect configured with the given aggregations.
func (_q *RbacPermissionGroupQuery) Aggregate(fns ...AggregateFunc) *RbacPermissionGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RbacPermissionGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rbacpermissiongroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RbacPermissionGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RbacPermissionGroup, error) {
	var (
		nodes       = []*RbacPermissionGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPermissions != nil,
			_q.withParent != nil,
			_q.withChildren != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RbacPermissionGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RbacPermissionGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPermissions; query != nil {
		if err := _q.loadPermissions(ctx, query, nodes,
			func(n *RbacPermissionGroup) { n.Edges.Permissions = []*RbacPermission{} },
			func(n *RbacPermissionGroup, e *RbacPermission) { n.Edges.Permissions = append(n.Edges.Permissions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *RbacPermissionGroup, e *RbacPermissionGroup) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *RbacPermissionGroup) { n.Edges.Children = []*RbacPermissionGroup{} },
			func(n *RbacPermissionGroup, e *RbacPermissionGroup) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RbacPermissionGroupQuery) loadPermissions(ctx context.Context, query *RbacPermissionQuery, nodes []*RbacPermissionGroup, init func(*RbacPermissionGroup), assign func(*RbacPermissionGroup, *RbacPermission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*RbacPermissionGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rbacpermission.FieldGroupID)
	}
	query.Where(predicate.RbacPermission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rbacpermissiongroup.PermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GroupID
		if fk == nil {
			return fmt.Errorf(`foreign-key "group_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "group_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RbacPermissionGroupQuery) loadParent(ctx context.Context, query *RbacPermissionGroupQuery, nodes []*RbacPermissionGroup, init func(*RbacPermissionGroup), assign func(*RbacPermissionGroup, *RbacPermissionGroup)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*RbacPermissionGroup)
	for i := range nodes {
		if nodes[i].ParentID == nil {
			continue
		}
		fk := *nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rbacpermissiongroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RbacPermissionGroupQuery) loadChildren(ctx context.Context, query *RbacPermissionGroupQuery, nodes []*RbacPermissionGroup, init func(*RbacPermissionGroup), assign func(*RbacPermissionGroup, *RbacPermissionGroup)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*RbacPermissionGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(rbacpermissiongroup.FieldParentID)
	}
	query.Where(predicate.RbacPermissionGroup(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rbacpermissiongroup.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RbacPermissionGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RbacPermissionGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rbacpermissiongroup.Table, rbacpermissiongroup.Columns, sqlgraph.NewFieldSpec(rbacpermissiongroup.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissiongroup.FieldID)
		for i := range fields {
			if fields[i] != rbacpermissiongroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(rbacpermissiongroup.FieldParentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RbacPermissionGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rbacpermissiongroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rbacpermissiongroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RbacPermissionGroupGroupBy is the group-by builder for RbacPermissionGroup entities.
type RbacPermissionGroupGroupBy struct {
	selector
	build *RbacPermissionGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RbacPermissionGroupGroupBy) Aggregate(fns ...AggregateFunc) *RbacPermissionGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RbacPermissionGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RbacPermissionGroupQuery, *RbacPermissionGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RbacPermissionGroupGroupBy) sqlScan(ctx context.Context, root *RbacPermissionGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RbacPermissionGroupSelect is the builder for selecting fields of RbacPermissionGroup entities.
type RbacPermissionGroupSelect struct {
	*RbacPermissionGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RbacPermissionGroupSelect) Aggregate(fns ...AggregateFunc) *RbacPermissionGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RbacPermissionGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RbacPermissionGroupQuery, *RbacPermissionGroupSelect](ctx, _s.RbacPermissionGroupQuery, _s, _s.inters, v)
}

func (_s *RbacPermissionGroupSelect) sqlScan(ctx context.Context, root *RbacPermissionGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
