// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacmenu"
	"github.com/google/uuid"
)

// RbacMenu is the model entity for the RbacMenu schema.
type RbacMenu struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type rbacmenu.Type `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Path holds the value of the "path" field.
	Path *string `json:"path,omitempty"`
	// Component holds the value of the "component" field.
	Component *string `json:"component,omitempty"`
	// Redirect holds the value of the "redirect" field.
	Redirect *string `json:"redirect,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta *string `json:"meta,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *uuid.UUID `json:"parent_id,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort,omitempty"`
	// Status holds the value of the "status" field.
	Status rbacmenu.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RbacMenuQuery when eager-loading is set.
	Edges        RbacMenuEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RbacMenuEdges holds the relations/edges for other nodes in the graph.
type RbacMenuEdges struct {
	// Parent holds the value of the parent edge.
	Parent *RbacMenu `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*RbacMenu `json:"children,omitempty"`
	// PermissionMenus holds the value of the permission_menus edge.
	PermissionMenus []*RbacPermissionMenu `json:"permission_menus,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacMenuEdges) ParentOrErr() (*RbacMenu, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rbacmenu.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e RbacMenuEdges) ChildrenOrErr() ([]*RbacMenu, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// PermissionMenusOrErr returns the PermissionMenus value or an error if the edge
// was not loaded in eager-loading.
func (e RbacMenuEdges) PermissionMenusOrErr() ([]*RbacPermissionMenu, error) {
	if e.loadedTypes[2] {
		return e.PermissionMenus, nil
	}
	return nil, &NotLoadedError{edge: "permission_menus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacMenu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacmenu.FieldParentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rbacmenu.FieldSort:
			values[i] = new(sql.NullInt64)
		case rbacmenu.FieldType, rbacmenu.FieldName, rbacmenu.FieldPath, rbacmenu.FieldComponent, rbacmenu.FieldRedirect, rbacmenu.FieldMeta, rbacmenu.FieldStatus:
			values[i] = new(sql.NullString)
		case rbacmenu.FieldCreatedAt, rbacmenu.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case rbacmenu.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacMenu fields.
func (_m *RbacMenu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacmenu.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rbacmenu.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = rbacmenu.Type(value.String)
			}
		case rbacmenu.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case rbacmenu.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = new(string)
				*_m.Path = value.String
			}
		case rbacmenu.FieldComponent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field component", values[i])
			} else if value.Valid {
				_m.Component = new(string)
				*_m.Component = value.String
			}
		case rbacmenu.FieldRedirect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect", values[i])
			} else if value.Valid {
				_m.Redirect = new(string)
				*_m.Redirect = value.String
			}
		case rbacmenu.FieldMeta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value.Valid {
				_m.Meta = new(string)
				*_m.Meta = value.String
			}
		case rbacmenu.FieldParentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(uuid.UUID)
				*_m.ParentID = *value.S.(*uuid.UUID)
			}
		case rbacmenu.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case rbacmenu.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = rbacmenu.Status(value.String)
			}
		case rbacmenu.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rbacmenu.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacMenu.
// This includes values selected through modifiers, order, etc.
func (_m *RbacMenu) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the RbacMenu entity.
func (_m *RbacMenu) QueryParent() *RbacMenuQuery {
	return NewRbacMenuClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the RbacMenu entity.
func (_m *RbacMenu) QueryChildren() *RbacMenuQuery {
	return NewRbacMenuClient(_m.config).QueryChildren(_m)
}

// QueryPermissionMenus queries the "permission_menus" edge of the RbacMenu entity.
func (_m *RbacMenu) QueryPermissionMenus() *RbacPermissionMenuQuery {
	return NewRbacMenuClient(_m.config).QueryPermissionMenus(_m)
}

// Update returns a builder for updating this RbacMenu.
// Note that you need to call RbacMenu.Unwrap() before calling this method if this RbacMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacMenu) Update() *RbacMenuUpdateOne {
	return NewRbacMenuClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacMenu) Unwrap() *RbacMenu {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacMenu is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacMenu) String() string {
	var builder strings.Builder
	builder.WriteString("RbacMenu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Path; v != nil {
		builder.WriteString("path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Component; v != nil {
		builder.WriteString("component=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Redirect; v != nil {
		builder.WriteString("redirect=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Meta; v != nil {
		builder.WriteString("meta=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RbacMenus is a parsable slice of RbacMenu.
type RbacMenus []*RbacMenu
