// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacmenu"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionmenu"
	"github.com/google/uuid"
)

// RbacPermissionMenu is the model entity for the RbacPermissionMenu schema.
type RbacPermissionMenu struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID uuid.UUID `json:"permission_id,omitempty"`
	// MenuID holds the value of the "menu_id" field.
	MenuID uuid.UUID `json:"menu_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RbacPermissionMenuQuery when eager-loading is set.
	Edges        RbacPermissionMenuEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RbacPermissionMenuEdges holds the relations/edges for other nodes in the graph.
type RbacPermissionMenuEdges struct {
	// Permission holds the value of the permission edge.
	Permission *RbacPermission `json:"permission,omitempty"`
	// Menu holds the value of the menu edge.
	Menu *RbacMenu `json:"menu,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacPermissionMenuEdges) PermissionOrErr() (*RbacPermission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rbacpermission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// MenuOrErr returns the Menu value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacPermissionMenuEdges) MenuOrErr() (*RbacMenu, error) {
	if e.Menu != nil {
		return e.Menu, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: rbacmenu.Label}
	}
	return nil, &NotLoadedError{edge: "menu"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacPermissionMenu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacpermissionmenu.FieldID, rbacpermissionmenu.FieldPermissionID, rbacpermissionmenu.FieldMenuID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacPermissionMenu fields.
func (_m *RbacPermissionMenu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacpermissionmenu.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rbacpermissionmenu.FieldPermissionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value != nil {
				_m.PermissionID = *value
			}
		case rbacpermissionmenu.FieldMenuID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field menu_id", values[i])
			} else if value != nil {
				_m.MenuID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacPermissionMenu.
// This includes values selected through modifiers, order, etc.
func (_m *RbacPermissionMenu) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermission queries the "permission" edge of the RbacPermissionMenu entity.
func (_m *RbacPermissionMenu) QueryPermission() *RbacPermissionQuery {
	return NewRbacPermissionMenuClient(_m.config).QueryPermission(_m)
}

// QueryMenu queries the "menu" edge of the RbacPermissionMenu entity.
func (_m *RbacPermissionMenu) QueryMenu() *RbacMenuQuery {
	return NewRbacPermissionMenuClient(_m.config).QueryMenu(_m)
}

// Update returns a builder for updating this RbacPermissionMenu.
// Note that you need to call RbacPermissionMenu.Unwrap() before calling this method if this RbacPermissionMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacPermissionMenu) Update() *RbacPermissionMenuUpdateOne {
	return NewRbacPermissionMenuClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacPermissionMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacPermissionMenu) Unwrap() *RbacPermissionMenu {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacPermissionMenu is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacPermissionMenu) String() string {
	var builder strings.Builder
	builder.WriteString("RbacPermissionMenu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("menu_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuID))
	builder.WriteByte(')')
	return builder.String()
}

// RbacPermissionMenus is a parsable slice of RbacPermissionMenu.
type RbacPermissionMenus []*RbacPermissionMenu
