// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacmenu"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermission"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/rbacpermissionmenu"
	"github.com/google/uuid"
)

// RbacPermissionMenuUpdate is the builder for updating RbacPermissionMenu entities.
type RbacPermissionMenuUpdate struct {
	config
	hooks    []Hook
	mutation *RbacPermissionMenuMutation
}

// Where appends a list predicates to the RbacPermissionMenuUpdate builder.
func (_u *RbacPermissionMenuUpdate) Where(ps ...predicate.RbacPermissionMenu) *RbacPermissionMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *RbacPermissionMenuUpdate) SetPermissionID(v uuid.UUID) *RbacPermissionMenuUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RbacPermissionMenuUpdate) SetNillablePermissionID(v *uuid.UUID) *RbacPermissionMenuUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *RbacPermissionMenuUpdate) SetMenuID(v uuid.UUID) *RbacPermissionMenuUpdate {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *RbacPermissionMenuUpdate) SetNillableMenuID(v *uuid.UUID) *RbacPermissionMenuUpdate {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetPermission sets the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionMenuUpdate) SetPermission(v *RbacPermission) *RbacPermissionMenuUpdate {
	return _u.SetPermissionID(v.ID)
}

// SetMenu sets the "menu" edge to the RbacMenu entity.
func (_u *RbacPermissionMenuUpdate) SetMenu(v *RbacMenu) *RbacPermissionMenuUpdate {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the RbacPermissionMenuMutation object of the builder.
func (_u *RbacPermissionMenuUpdate) Mutation() *RbacPermissionMenuMutation {
	return _u.mutation
}

// ClearPermission clears the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionMenuUpdate) ClearPermission() *RbacPermissionMenuUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// ClearMenu clears the "menu" edge to the RbacMenu entity.
func (_u *RbacPermissionMenuUpdate) ClearMenu() *RbacPermissionMenuUpdate {
	_u.mutation.ClearMenu()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacPermissionMenuUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacPermissionMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionMenuUpdate) check() error {
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionMenu.permission"`)
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionMenu.menu"`)
	}
	return nil
}

func (_u *RbacPermissionMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionmenu.Table, rbacpermissionmenu.Columns, sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionmenu.PermissionTable,
			Columns: []string{rbacpermissionmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionmenu.PermissionTable,
			Columns: []string{rbacpermissionmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rbacpermissionmenu.MenuTable,
			Columns: []string{rbacpermissionmenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacmenu.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rbacpermissionmenu.MenuTable,
			Columns: []string{rbacpermissionmenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacPermissionMenuUpdateOne is the builder for updating a single RbacPermissionMenu entity.
type RbacPermissionMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacPermissionMenuMutation
}

// SetPermissionID sets the "permission_id" field.
func (_u *RbacPermissionMenuUpdateOne) SetPermissionID(v uuid.UUID) *RbacPermissionMenuUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RbacPermissionMenuUpdateOne) SetNillablePermissionID(v *uuid.UUID) *RbacPermissionMenuUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *RbacPermissionMenuUpdateOne) SetMenuID(v uuid.UUID) *RbacPermissionMenuUpdateOne {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *RbacPermissionMenuUpdateOne) SetNillableMenuID(v *uuid.UUID) *RbacPermissionMenuUpdateOne {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetPermission sets the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionMenuUpdateOne) SetPermission(v *RbacPermission) *RbacPermissionMenuUpdateOne {
	return _u.SetPermissionID(v.ID)
}

// SetMenu sets the "menu" edge to the RbacMenu entity.
func (_u *RbacPermissionMenuUpdateOne) SetMenu(v *RbacMenu) *RbacPermissionMenuUpdateOne {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the RbacPermissionMenuMutation object of the builder.
func (_u *RbacPermissionMenuUpdateOne) Mutation() *RbacPermissionMenuMutation {
	return _u.mutation
}

// ClearPermission clears the "permission" edge to the RbacPermission entity.
func (_u *RbacPermissionMenuUpdateOne) ClearPermission() *RbacPermissionMenuUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// ClearMenu clears the "menu" edge to the RbacMenu entity.
func (_u *RbacPermissionMenuUpdateOne) ClearMenu() *RbacPermissionMenuUpdateOne {
	_u.mutation.ClearMenu()
	return _u
}

// Where appends a list predicates to the RbacPermissionMenuUpdate builder.
func (_u *RbacPermissionMenuUpdateOne) Where(ps ...predicate.RbacPermissionMenu) *RbacPermissionMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacPermissionMenuUpdateOne) Select(field string, fields ...string) *RbacPermissionMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacPermissionMenu entity.
func (_u *RbacPermissionMenuUpdateOne) Save(ctx context.Context) (*RbacPermissionMenu, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacPermissionMenuUpdateOne) SaveX(ctx context.Context) *RbacPermissionMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacPermissionMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacPermissionMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacPermissionMenuUpdateOne) check() error {
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionMenu.permission"`)
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RbacPermissionMenu.menu"`)
	}
	return nil
}

func (_u *RbacPermissionMenuUpdateOne) sqlSave(ctx context.Context) (_node *RbacPermissionMenu, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacpermissionmenu.Table, rbacpermissionmenu.Columns, sqlgraph.NewFieldSpec(rbacpermissionmenu.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacPermissionMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacpermissionmenu.FieldID)
		for _, f := range fields {
			if !rbacpermissionmenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacpermissionmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionmenu.PermissionTable,
			Columns: []string{rbacpermissionmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacpermissionmenu.PermissionTable,
			Columns: []string{rbacpermissionmenu.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rbacpermissionmenu.MenuTable,
			Columns: []string{rbacpermissionmenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacmenu.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rbacpermissionmenu.MenuTable,
			Columns: []string{rbacpermissionmenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacmenu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RbacPermissionMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacpermissionmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
