package main

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func generateTypeScriptFile(gen *protogen.Plugin, file *protogen.File, resources []*resourceInfo) {
	filename := file.GeneratedFilenamePrefix + ".crud.ts"
	generated := gen.NewGeneratedFile(filename, file.GoImportPath)
	generated.P("// Code generated by protoc-gen-servora-crud. DO NOT EDIT.")
	generated.P()
	generated.P(`import { ResourceNameError } from "@servora/proto-utils/crud";`)
	generated.P()
	generated.P("function assertResourceSegment(resource: string, variable: string, value: string): void {")
	generated.P(`  if (value.length === 0 || value.includes("/")) {`)
	generated.P("    throw new ResourceNameError(`${resource} variable ${variable} must be non-empty and contain no slash`);")
	generated.P("  }")
	generated.P("}")
	generated.P()
	for index, resource := range resources {
		if index > 0 {
			generated.P()
		}
		generateTypeScriptResource(generated, resource)
	}
}

func generateTypeScriptResource(g *protogen.GeneratedFile, resource *resourceInfo) {
	name := resource.message.GoIdent.GoName
	partsType := name + "NameParts"
	multiPattern := len(resource.patterns) > 1
	g.P("export type ", partsType, " =")
	for index, pattern := range resource.patterns {
		if !multiPattern && index > 0 {
			break
		}
		g.P("  ", mapStart(index), "{")
		if multiPattern {
			g.P("    readonly pattern: ", strconv.Quote(pattern.raw), ";")
		}
		for _, variable := range pattern.variables {
			g.P("    readonly ", variable, ": string;")
		}
		suffix := ""
		if index == len(resource.patterns)-1 {
			suffix = ";"
		}
		g.P("  }", suffix)
	}
	g.P()
	g.P("export const ", name, "Name = {")
	g.P("  format(parts: ", partsType, "): string {")
	if multiPattern {
		g.P("    switch (parts.pattern) {")
		for _, pattern := range resource.patterns {
			g.P("      case ", strconv.Quote(pattern.raw), ":")
			generateTypeScriptNameValidation(g, name, pattern, "        ")
			g.P("        return ", tsPatternArray(pattern, "parts"), `.join("/");`)
		}
		g.P("      default:")
		g.P("        throw new ResourceNameError(\"", name, " resource name pattern is not selected\");")
		g.P("    }")
	} else {
		generateTypeScriptNameValidation(g, name, resource.patterns[0], "    ")
		g.P("    return ", tsPatternArray(resource.patterns[0], "parts"), `.join("/");`)
	}
	g.P("  },")
	g.P("  parse(value: string): ", partsType, " {")
	g.P(`    const segments = value.split("/");`)
	for _, pattern := range resource.patterns {
		conditions := []string{fmt.Sprintf("segments.length === %d", len(pattern.segments))}
		for index, segment := range pattern.segments {
			if segment.literal != "" {
				conditions = append(conditions, fmt.Sprintf("segments[%d] === %s", index, strconv.Quote(segment.literal)))
			}
		}
		g.P("    if (", strings.Join(conditions, " && "), ") {")
		for index, segment := range pattern.segments {
			if segment.variable != "" {
				g.P("      assertResourceSegment(", strconv.Quote(name), ", ", strconv.Quote(segment.variable), ", segments[", index, "]!);")
			}
		}
		g.P("      return {")
		if multiPattern {
			g.P("        pattern: ", strconv.Quote(pattern.raw), ",")
		}
		for index, segment := range pattern.segments {
			if segment.variable != "" {
				g.P("        ", segment.variable, ": segments[", index, "]!,")
			}
		}
		g.P("      };")
		g.P("    }")
	}
	g.P("    throw new ResourceNameError(`invalid ", name, " resource name ${value}`);")
	g.P("  },")
	g.P("  tryParse(value: string): ", partsType, " | null {")
	g.P("    try {")
	g.P("      return this.parse(value);")
	g.P("    } catch {")
	g.P("      return null;")
	g.P("    }")
	g.P("  },")
	g.P("} as const;")
	g.P()
	g.P("export const ", name, "Fields = {")
	for _, field := range resource.fields {
		g.P("  ", lowerFirst(field.symbol), ": ", strconv.Quote(field.path), ",")
	}
	g.P("} as const;")
	g.P()
	g.P("export const ", name, "UpdateFields = {")
	for _, field := range resource.writable {
		g.P("  ", lowerFirst(field.symbol), ": ", strconv.Quote(field.path), ",")
	}
	g.P("} as const;")
}

func generateTypeScriptNameValidation(g *protogen.GeneratedFile, resource string, pattern namePattern, indent string) {
	for _, variable := range pattern.variables {
		g.P(indent, "assertResourceSegment(", strconv.Quote(resource), ", ", strconv.Quote(variable), ", parts.", variable, ");")
	}
}

func tsPatternArray(pattern namePattern, value string) string {
	parts := make([]string, 0, len(pattern.segments))
	for _, segment := range pattern.segments {
		if segment.literal != "" {
			parts = append(parts, strconv.Quote(segment.literal))
		} else {
			parts = append(parts, value+"."+segment.variable)
		}
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func mapStart(index int) string {
	if index == 0 {
		return ""
	}
	return "| "
}
