// Package crud binds backend-neutral CRUD list queries to Ent SQL builders.
package crud

import (
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	corecrud "github.com/Servora-Kit/servora/core/crud"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// FieldPath is the descriptor-backed path generated by protoc-gen-servora-crud.
type FieldPath interface {
	String() string
	Descriptor() protoreflect.FieldDescriptor
}

// ValidColumn reports whether a name belongs to one generated Ent table.
type ValidColumn func(string) bool

// ListFieldsOption contributes one immutable ListFields configuration entry.
type ListFieldsOption interface {
	apply(*listFieldsBuilder) error
}

type listFieldsOptionFunc func(*listFieldsBuilder) error

func (option listFieldsOptionFunc) apply(builder *listFieldsBuilder) error { return option(builder) }

type bindingKind uint8

const (
	bindingColumn bindingKind = iota
	bindingJSONPath
	bindingCustom
)

// QueryConverter converts one descriptor-checked filter literal to its backend representation.
type QueryConverter func(corecrud.FilterValue) (any, error)

// SelectorPredicate builds one predicate against the concrete Ent selector at execution time.
type SelectorPredicate func(*sql.Selector) *sql.Predicate

// CustomPredicate validates one typed comparison before database access and returns its selector factory.
type CustomPredicate func(corecrud.FilterOperator, corecrud.FilterValue) (SelectorPredicate, error)

// CursorConverter normalizes one Ent-selected backend value for page-token encoding.
type CursorConverter func(any) (any, error)

// CustomOrderExpression provides one application-owned, deterministic SQL sort expression.
type CustomOrderExpression func(*sql.Selector) sql.Querier

type cursorExtractor func(any, string) (any, error)

// Binding maps one public resource field path to one Ent query source.
// Fluent methods return modified copies; they never mutate an installed ListFields.
type Binding struct {
	path               string
	descriptor         protoreflect.FieldDescriptor
	column             string
	kind               bindingKind
	jsonPath           []string
	customPredicate    CustomPredicate
	customOrder        CustomOrderExpression
	cursorExtractorSet bool
	cursorExtractor    cursorExtractor
	queryConverterSet  bool
	queryConverter     QueryConverter
	cursorConverterSet bool
	cursorConverter    CursorConverter
	filter             bool
	order              bool
	nullable           bool
	profileID          string
}

// Bind maps one generated resource field path to one generated Ent column constant.
func Bind(path FieldPath, column string) Binding {
	return Binding{
		path: fieldPathString(path), descriptor: fieldPathDescriptor(path),
		column: column, kind: bindingColumn,
	}
}

// JSONPath maps one resource leaf to a path inside a generated Ent JSON column.
func JSONPath(path FieldPath, column string, jsonPath ...string) Binding {
	return Binding{
		path: fieldPathString(path), descriptor: fieldPathDescriptor(path),
		column: column, kind: bindingJSONPath, jsonPath: append([]string(nil), jsonPath...),
	}
}

// Custom maps one resource field to an application-owned predicate translator.
// key is a stable repository-local binding identity, not a client-visible field.
func Custom(path FieldPath, key string, predicate CustomPredicate) Binding {
	return Binding{
		path: fieldPathString(path), descriptor: fieldPathDescriptor(path),
		column: key, kind: bindingCustom, customPredicate: predicate,
	}
}

// CustomOrder binds a computed, relation, JSON-expression, or other non-column sort key.
// extractor is mandatory because only the repository can recover the typed cursor value.
func CustomOrder[PO any](
	path FieldPath,
	key string,
	expression CustomOrderExpression,
	extractor func(PO, string) (any, error),
) Binding {
	binding := Binding{
		path: fieldPathString(path), descriptor: fieldPathDescriptor(path),
		column: key, kind: bindingCustom, customOrder: expression, order: true,
	}
	if extractor == nil {
		return binding
	}
	binding.cursorExtractorSet = true
	binding.cursorExtractor = func(value any, alias string) (any, error) {
		typed, ok := value.(PO)
		if !ok {
			return nil, fmt.Errorf("entcrud: custom cursor extractor received %T, want %T", value, *new(PO))
		}
		return extractor(typed, alias)
	}
	return binding
}

// Filter enables the logical type's built-in safe filter operators.
func (binding Binding) Filter() Binding {
	binding.filter = true
	return binding
}

// Order enables deterministic ordering and keyset pagination for this binding.
func (binding Binding) Order() Binding {
	binding.order = true
	return binding
}

// Nullable declares that the backend column can contain SQL NULL.
func (binding Binding) Nullable() Binding {
	binding.nullable = true
	return binding
}

// WithComparisonProfile replaces the built-in comparison profile identity.
// The profile must be stable and versioned; changing it invalidates old page tokens.
func (binding Binding) WithComparisonProfile(profileID string) Binding {
	binding.profileID = profileID
	return binding
}

// WithQueryConverter converts typed Proto literals when storage uses another representation.
func (binding Binding) WithQueryConverter(converter QueryConverter) Binding {
	binding.queryConverter = converter
	binding.queryConverterSet = true
	return binding
}

// WithCursorConverter converts selected backend values when storage differs from the Proto logical type.
func (binding Binding) WithCursorConverter(converter CursorConverter) Binding {
	binding.cursorConverter = converter
	binding.cursorConverterSet = true
	return binding
}

func (binding Binding) apply(builder *listFieldsBuilder) error {
	builder.bindings = append(builder.bindings, binding)
	return nil
}

type configuredDefaultOrder struct {
	path      string
	direction corecrud.OrderDirection
}

type valueConverter func(any) (any, error)

type configuredCursorKey struct {
	column      string
	direction   corecrud.OrderDirection
	logicalType corecrud.LogicalType
	profileID   string
	converter   valueConverter
}

// Columns installs the generated Ent column allowlist for this table.
func Columns(valid ValidColumn) ListFieldsOption {
	return listFieldsOptionFunc(func(builder *listFieldsBuilder) error {
		if valid == nil {
			return fmt.Errorf("entcrud: column validator is nil")
		}
		if builder.validColumn != nil {
			return fmt.Errorf("entcrud: column validator is configured more than once")
		}
		builder.validColumn = valid
		return nil
	})
}

// DefaultOrder appends one repository default order term.
func DefaultOrder(path FieldPath, direction corecrud.OrderDirection) ListFieldsOption {
	return listFieldsOptionFunc(func(builder *listFieldsBuilder) error {
		builder.defaults = append(builder.defaults, configuredDefaultOrder{
			path: fieldPathString(path), direction: direction,
		})
		return nil
	})
}

// CursorKeyBinding is one not-yet-installed hidden cursor-key declaration.
type CursorKeyBinding[T any] struct {
	configured configuredCursorKey
	err        error
}

// CursorKey declares one non-null hidden backend key used to make pagination unique.
func CursorKey[T any](column string, direction corecrud.OrderDirection) CursorKeyBinding[T] {
	logicalType, err := cursorLogicalType[T]()
	return CursorKeyBinding[T]{
		configured: configuredCursorKey{
			column: column, direction: direction, logicalType: logicalType,
			profileID: defaultComparisonProfile(logicalType),
		},
		err: err,
	}
}

// WithConverter installs an explicit storage-value to cursor-value conversion.
func (binding CursorKeyBinding[T]) WithConverter(converter func(any) (T, error)) CursorKeyBinding[T] {
	if converter == nil {
		binding.err = errors.New("entcrud: cursor key converter is nil")
		return binding
	}
	binding.configured.converter = func(value any) (any, error) { return converter(value) }
	return binding
}

func (binding CursorKeyBinding[T]) apply(builder *listFieldsBuilder) error {
	if binding.err != nil {
		return binding.err
	}
	builder.cursorKeys = append(builder.cursorKeys, binding.configured)
	return nil
}

type listFieldsBuilder struct {
	validColumn ValidColumn
	bindings    []Binding
	defaults    []configuredDefaultOrder
	cursorKeys  []configuredCursorKey
}

// ListFields is one validated, immutable resource-to-Ent query contract.
type ListFields[PO any] struct {
	bindings       map[string]fieldBinding
	orderSources   map[string]fieldBinding
	orderAssembler *corecrud.OrderAssembler
	cursorKeys     []configuredCursorKey
}

type fieldBinding struct {
	path               string
	descriptor         protoreflect.FieldDescriptor
	column             string
	kind               bindingKind
	jsonPath           []string
	customPredicate    CustomPredicate
	customOrder        CustomOrderExpression
	cursorExtractorSet bool
	cursorExtractor    cursorExtractor
	queryConverterSet  bool
	queryConverter     QueryConverter
	cursorConverterSet bool
	cursorConverter    CursorConverter
	filter             bool
	order              bool
	nullable           bool
	logicalType        corecrud.LogicalType
	profileID          string
	orderBinding       corecrud.OrderBinding
}

// NewListFields validates and freezes all field, default-order, and cursor-key declarations.
func NewListFields[PO any](options ...ListFieldsOption) (*ListFields[PO], error) {
	builder := new(listFieldsBuilder)
	for index, option := range options {
		if isNilOption(option) {
			return nil, fmt.Errorf("entcrud: option %d is nil", index)
		}
		if err := option.apply(builder); err != nil {
			return nil, fmt.Errorf("entcrud: option %d: %w", index, err)
		}
	}
	if builder.validColumn == nil {
		return nil, fmt.Errorf("entcrud: Columns is required")
	}

	fields := &ListFields[PO]{
		bindings:     make(map[string]fieldBinding, len(builder.bindings)),
		orderSources: make(map[string]fieldBinding, len(builder.bindings)+len(builder.cursorKeys)),
		cursorKeys:   append([]configuredCursorKey(nil), builder.cursorKeys...),
	}
	orderBindings := make(map[string]corecrud.OrderBinding, len(builder.bindings))
	for index, configured := range builder.bindings {
		binding, err := buildFieldBinding(builder.validColumn, configured)
		if err != nil {
			return nil, fmt.Errorf("entcrud: binding %d: %w", index, err)
		}
		if binding.customOrder != nil {
			probe := sql.Select().From(sql.Table("_servora_list_fields_probe"))
			if binding.customOrder(probe) == nil {
				return nil, fmt.Errorf("entcrud: binding %d custom order expression returned nil", index)
			}
		}
		if _, duplicate := fields.bindings[binding.path]; duplicate {
			return nil, fmt.Errorf("entcrud: field %q is bound more than once", binding.path)
		}
		fields.bindings[binding.path] = binding
		if binding.order {
			if _, duplicate := fields.orderSources[binding.column]; duplicate {
				return nil, fmt.Errorf("entcrud: order backend key %q is bound more than once", binding.column)
			}
			orderBindings[binding.path] = binding.orderBinding
			fields.orderSources[binding.column] = binding
		}
	}

	defaults := make([]corecrud.ConfiguredOrderTerm, 0, len(builder.defaults))
	seenDefaults := make(map[string]struct{}, len(builder.defaults))
	for index, configured := range builder.defaults {
		binding, ok := fields.bindings[configured.path]
		if !ok {
			return nil, fmt.Errorf("entcrud: default order %d field %q is not bound", index, configured.path)
		}
		if !binding.order {
			return nil, fmt.Errorf("entcrud: default order %d field %q has no Order capability", index, configured.path)
		}
		if _, duplicate := seenDefaults[binding.column]; duplicate {
			return nil, fmt.Errorf("entcrud: default order column %q is duplicated", binding.column)
		}
		seenDefaults[binding.column] = struct{}{}
		defaults = append(defaults, corecrud.NewConfiguredOrderTerm(binding.orderBinding, configured.direction))
	}

	cursorTerms := make([]corecrud.ConfiguredOrderTerm, 0, len(builder.cursorKeys))
	seenCursor := make(map[string]struct{}, len(builder.cursorKeys))
	for index, configured := range builder.cursorKeys {
		if strings.TrimSpace(configured.column) == "" {
			return nil, fmt.Errorf("entcrud: cursor key %d column is empty", index)
		}
		if !builder.validColumn(configured.column) {
			return nil, fmt.Errorf("entcrud: cursor key %d column %q is not generated for this table", index, configured.column)
		}
		if _, duplicate := seenCursor[configured.column]; duplicate {
			return nil, fmt.Errorf("entcrud: cursor key column %q is duplicated", configured.column)
		}
		seenCursor[configured.column] = struct{}{}
		binding, err := corecrud.NewTypedOrderBinding(
			configured.column, "", false, configured.profileID, configured.logicalType,
		)
		if err != nil {
			return nil, fmt.Errorf("entcrud: cursor key %d: %w", index, err)
		}
		if existing, exists := fields.orderSources[configured.column]; exists {
			if existing.nullable || existing.logicalType != configured.logicalType || existing.profileID != configured.profileID {
				return nil, fmt.Errorf("entcrud: cursor key %q conflicts with its public order binding", configured.column)
			}
			if existing.cursorConverterSet && configured.converter != nil {
				return nil, fmt.Errorf("entcrud: cursor key %q configures two cursor converters", configured.column)
			}
			if configured.converter != nil {
				existing.cursorConverter = CursorConverter(configured.converter)
				existing.cursorConverterSet = true
				fields.orderSources[configured.column] = existing
			}
		} else {
			fields.orderSources[configured.column] = fieldBinding{
				column: configured.column, kind: bindingColumn,
				logicalType: configured.logicalType, profileID: configured.profileID,
				cursorConverter: CursorConverter(configured.converter), cursorConverterSet: configured.converter != nil,
			}
		}
		cursorTerms = append(cursorTerms, corecrud.NewConfiguredOrderTerm(binding, configured.direction))
	}

	assembler, err := corecrud.NewOrderAssembler(orderBindingResolver(orderBindings), defaults, cursorTerms)
	if err != nil {
		return nil, fmt.Errorf("entcrud: list order: %w", err)
	}
	fields.orderAssembler = assembler
	return fields, nil
}

// ResolveOrderBinding implements core/crud.OrderBindingResolver.
func (fields *ListFields[PO]) ResolveOrderBinding(field corecrud.FieldPlan) (corecrud.OrderBinding, bool) {
	if fields == nil {
		return corecrud.OrderBinding{}, false
	}
	binding, ok := fields.bindings[field.Path()]
	if !ok || !binding.order || binding.descriptor.FullName() != field.Descriptor().FullName() {
		return corecrud.OrderBinding{}, false
	}
	return binding.orderBinding, true
}

type orderBindingResolver map[string]corecrud.OrderBinding

func (resolver orderBindingResolver) ResolveOrderBinding(field corecrud.FieldPlan) (corecrud.OrderBinding, bool) {
	binding, ok := resolver[field.Path()]
	return binding, ok
}

func buildFieldBinding(valid ValidColumn, configured Binding) (fieldBinding, error) {
	if strings.TrimSpace(configured.path) == "" {
		return fieldBinding{}, fmt.Errorf("resource field path is empty")
	}
	if configured.descriptor == nil {
		return fieldBinding{}, fmt.Errorf("resource field %q descriptor is nil", configured.path)
	}
	if strings.TrimSpace(configured.column) == "" {
		return fieldBinding{}, fmt.Errorf("field %q backend key is empty", configured.path)
	}
	if configured.kind != bindingCustom && !valid(configured.column) {
		return fieldBinding{}, fmt.Errorf("field %q backend column %q is not generated for this table", configured.path, configured.column)
	}
	if !configured.filter && !configured.order {
		return fieldBinding{}, fmt.Errorf("field %q enables neither Filter nor Order", configured.path)
	}
	if configured.kind == bindingJSONPath {
		if len(configured.jsonPath) == 0 {
			return fieldBinding{}, fmt.Errorf("field %q JSON path is empty", configured.path)
		}
		for index, part := range configured.jsonPath {
			if strings.TrimSpace(part) == "" {
				return fieldBinding{}, fmt.Errorf("field %q JSON path part %d is empty", configured.path, index)
			}
		}
	}
	if configured.kind == bindingCustom && configured.filter && configured.customPredicate == nil {
		return fieldBinding{}, fmt.Errorf("field %q custom predicate is nil", configured.path)
	}
	if configured.queryConverterSet && configured.queryConverter == nil {
		return fieldBinding{}, fmt.Errorf("field %q query converter is nil", configured.path)
	}
	if configured.kind == bindingCustom && configured.order && configured.customOrder == nil {
		return fieldBinding{}, fmt.Errorf("field %q custom order expression is nil", configured.path)
	}
	if configured.kind == bindingCustom && configured.order && (!configured.cursorExtractorSet || configured.cursorExtractor == nil) {
		return fieldBinding{}, fmt.Errorf("field %q custom order requires a typed cursor extractor", configured.path)
	}
	logicalType, err := descriptorLogicalType(configured.descriptor)
	if err != nil {
		return fieldBinding{}, fmt.Errorf("field %q: %w", configured.path, err)
	}
	if configured.descriptor.IsList() && configured.kind == bindingColumn {
		return fieldBinding{}, fmt.Errorf("field %q repeated values require JSONPath or Custom binding", configured.path)
	}
	if configured.cursorConverterSet && configured.cursorConverter == nil {
		return fieldBinding{}, fmt.Errorf("field %q cursor converter is nil", configured.path)
	}
	if configured.order && !orderableLogicalType(logicalType) {
		return fieldBinding{}, fmt.Errorf("field %q logical type %q cannot use built-in order", configured.path, logicalType)
	}
	profileID := configured.profileID
	if profileID == "" {
		profileID = defaultComparisonProfile(logicalType)
	}
	if strings.TrimSpace(profileID) == "" {
		return fieldBinding{}, fmt.Errorf("field %q comparison profile is empty", configured.path)
	}
	result := fieldBinding{
		path: configured.path, descriptor: configured.descriptor, column: configured.column,
		kind: configured.kind, jsonPath: append([]string(nil), configured.jsonPath...),
		customPredicate: configured.customPredicate, customOrder: configured.customOrder,
		queryConverter: configured.queryConverter, queryConverterSet: configured.queryConverterSet,
		cursorConverter: configured.cursorConverter, cursorConverterSet: configured.cursorConverterSet,
		cursorExtractor: configured.cursorExtractor, cursorExtractorSet: configured.cursorExtractorSet,
		filter: configured.filter, order: configured.order, nullable: configured.nullable,
		logicalType: logicalType, profileID: profileID,
	}
	if configured.order {
		result.orderBinding, err = corecrud.NewTypedOrderBinding(
			configured.column, configured.path, configured.nullable, profileID, logicalType,
		)
		if err != nil {
			return fieldBinding{}, err
		}
	}
	return result, nil
}

func descriptorLogicalType(descriptor protoreflect.FieldDescriptor) (corecrud.LogicalType, error) {
	if descriptor.IsMap() {
		return "", fmt.Errorf("map fields require a custom binding")
	}
	kind := descriptor.Kind()
	if descriptor.IsList() {
		switch kind {
		case protoreflect.StringKind, protoreflect.BoolKind, protoreflect.EnumKind,
			protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
			protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
			protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
			protoreflect.Uint64Kind, protoreflect.Fixed64Kind,
			protoreflect.FloatKind, protoreflect.DoubleKind:
		default:
			return "", fmt.Errorf("repeated message/bytes fields require a custom binding")
		}
	}
	switch kind {
	case protoreflect.StringKind:
		return corecrud.LogicalString, nil
	case protoreflect.BoolKind:
		return corecrud.LogicalBool, nil
	case protoreflect.EnumKind:
		return corecrud.LogicalEnum, nil
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return corecrud.LogicalInt32, nil
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return corecrud.LogicalInt64, nil
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return corecrud.LogicalUint32, nil
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return corecrud.LogicalUint64, nil
	case protoreflect.FloatKind:
		return corecrud.LogicalFloat32, nil
	case protoreflect.DoubleKind:
		return corecrud.LogicalFloat64, nil
	case protoreflect.BytesKind:
		return corecrud.LogicalBytes, nil
	case protoreflect.MessageKind:
		switch descriptor.Message().FullName() {
		case "google.protobuf.Timestamp":
			return corecrud.LogicalTimestamp, nil
		case "google.protobuf.Duration":
			return corecrud.LogicalDuration, nil
		default:
			return "", fmt.Errorf("message fields require a leaf or custom binding")
		}
	default:
		return "", fmt.Errorf("protobuf kind %s is unsupported", kind)
	}
}

func cursorLogicalType[T any]() (corecrud.LogicalType, error) {
	var value T
	typeOf := reflect.TypeOf(value)
	if typeOf == reflect.TypeFor[[]byte]() {
		return corecrud.LogicalBytes, nil
	}
	if typeOf == reflect.TypeFor[time.Time]() {
		return corecrud.LogicalTimestamp, nil
	}
	if typeOf == reflect.TypeFor[time.Duration]() {
		return corecrud.LogicalDuration, nil
	}
	if typeOf == nil {
		return "", fmt.Errorf("entcrud: cursor key type is nil or unsupported")
	}
	switch typeOf.Kind() {
	case reflect.String:
		return corecrud.LogicalString, nil
	case reflect.Bool:
		return corecrud.LogicalBool, nil
	case reflect.Int32:
		return corecrud.LogicalInt32, nil
	case reflect.Int, reflect.Int64:
		return corecrud.LogicalInt64, nil
	case reflect.Uint32:
		return corecrud.LogicalUint32, nil
	case reflect.Uint, reflect.Uint64:
		return corecrud.LogicalUint64, nil
	case reflect.Float32:
		return corecrud.LogicalFloat32, nil
	case reflect.Float64:
		return corecrud.LogicalFloat64, nil
	default:
		return "", fmt.Errorf("entcrud: cursor key Go type %s is unsupported", typeOf)
	}
}

func orderableLogicalType(logicalType corecrud.LogicalType) bool {
	return logicalType != corecrud.LogicalBytes
}

func defaultComparisonProfile(logicalType corecrud.LogicalType) string {
	if logicalType == corecrud.LogicalString {
		return "proto/string:utf8-binary:v1"
	}
	if logicalType == corecrud.LogicalEnum {
		return "proto/enum-number:v1"
	}
	return "proto/" + string(logicalType) + ":v1"
}

func fieldPathString(path FieldPath) string {
	if isNilFieldPath(path) {
		return ""
	}
	return path.String()
}

func fieldPathDescriptor(path FieldPath) protoreflect.FieldDescriptor {
	if isNilFieldPath(path) {
		return nil
	}
	return path.Descriptor()
}

func isNilFieldPath(path FieldPath) bool {
	if path == nil {
		return true
	}
	value := reflect.ValueOf(path)
	return value.Kind() == reflect.Pointer && value.IsNil()
}

func isNilOption(option ListFieldsOption) bool {
	if option == nil {
		return true
	}
	value := reflect.ValueOf(option)
	return value.Kind() == reflect.Func && value.IsNil()
}
