// Code generated by ent, DO NOT EDIT.

package entfixture

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	crudpb "github.com/Servora-Kit/servora/api/gen/go/servora/crud/v1"
	"github.com/Servora-Kit/servora/contrib/db/entgo/crud/testdata/entfixture/contractrow"
)

// ContractRowCreate is the builder for creating a ContractRow entity.
type ContractRowCreate struct {
	config
	mutation *ContractRowMutation
	hooks    []Hook
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ContractRowCreate) SetDeleteTime(v time.Time) *ContractRowCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableDeleteTime(v *time.Time) *ContractRowCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *ContractRowCreate) SetDeletedBy(v string) *ContractRowCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableDeletedBy(v *string) *ContractRowCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetPurgeTime sets the "purge_time" field.
func (_c *ContractRowCreate) SetPurgeTime(v time.Time) *ContractRowCreate {
	_c.mutation.SetPurgeTime(v)
	return _c
}

// SetNillablePurgeTime sets the "purge_time" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillablePurgeTime(v *time.Time) *ContractRowCreate {
	if v != nil {
		_c.SetPurgeTime(*v)
	}
	return _c
}

// SetTextValue sets the "text_value" field.
func (_c *ContractRowCreate) SetTextValue(v string) *ContractRowCreate {
	_c.mutation.SetTextValue(v)
	return _c
}

// SetNillableTextValue sets the "text_value" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableTextValue(v *string) *ContractRowCreate {
	if v != nil {
		_c.SetTextValue(*v)
	}
	return _c
}

// SetUniqueText sets the "unique_text" field.
func (_c *ContractRowCreate) SetUniqueText(v string) *ContractRowCreate {
	_c.mutation.SetUniqueText(v)
	return _c
}

// SetNumericValue sets the "numeric_value" field.
func (_c *ContractRowCreate) SetNumericValue(v int32) *ContractRowCreate {
	_c.mutation.SetNumericValue(v)
	return _c
}

// SetNullableText sets the "nullable_text" field.
func (_c *ContractRowCreate) SetNullableText(v string) *ContractRowCreate {
	_c.mutation.SetNullableText(v)
	return _c
}

// SetNillableNullableText sets the "nullable_text" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableNullableText(v *string) *ContractRowCreate {
	if v != nil {
		_c.SetNullableText(*v)
	}
	return _c
}

// SetTimestampValue sets the "timestamp_value" field.
func (_c *ContractRowCreate) SetTimestampValue(v time.Time) *ContractRowCreate {
	_c.mutation.SetTimestampValue(v)
	return _c
}

// SetNillableTimestampValue sets the "timestamp_value" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableTimestampValue(v *time.Time) *ContractRowCreate {
	if v != nil {
		_c.SetTimestampValue(*v)
	}
	return _c
}

// SetUpdatedTimestamp sets the "updated_timestamp" field.
func (_c *ContractRowCreate) SetUpdatedTimestamp(v time.Time) *ContractRowCreate {
	_c.mutation.SetUpdatedTimestamp(v)
	return _c
}

// SetNillableUpdatedTimestamp sets the "updated_timestamp" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableUpdatedTimestamp(v *time.Time) *ContractRowCreate {
	if v != nil {
		_c.SetUpdatedTimestamp(*v)
	}
	return _c
}

// SetDurationValue sets the "duration_value" field.
func (_c *ContractRowCreate) SetDurationValue(v time.Duration) *ContractRowCreate {
	_c.mutation.SetDurationValue(v)
	return _c
}

// SetNillableDurationValue sets the "duration_value" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableDurationValue(v *time.Duration) *ContractRowCreate {
	if v != nil {
		_c.SetDurationValue(*v)
	}
	return _c
}

// SetEnumNumber sets the "enum_number" field.
func (_c *ContractRowCreate) SetEnumNumber(v crudpb.CrudErrorReason) *ContractRowCreate {
	_c.mutation.SetEnumNumber(v)
	return _c
}

// SetNillableEnumNumber sets the "enum_number" field if the given value is not nil.
func (_c *ContractRowCreate) SetNillableEnumNumber(v *crudpb.CrudErrorReason) *ContractRowCreate {
	if v != nil {
		_c.SetEnumNumber(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContractRowCreate) SetID(v uint32) *ContractRowCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ContractRowMutation object of the builder.
func (_c *ContractRowCreate) Mutation() *ContractRowMutation {
	return _c.mutation
}

// Save creates the ContractRow in the database.
func (_c *ContractRowCreate) Save(ctx context.Context) (*ContractRow, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContractRowCreate) SaveX(ctx context.Context) *ContractRow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractRowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractRowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContractRowCreate) defaults() error {
	if _, ok := _c.mutation.TextValue(); !ok {
		v := contractrow.DefaultTextValue
		_c.mutation.SetTextValue(v)
	}
	if _, ok := _c.mutation.TimestampValue(); !ok {
		if contractrow.DefaultTimestampValue == nil {
			return fmt.Errorf("entfixture: uninitialized contractrow.DefaultTimestampValue (forgotten import entfixture/runtime?)")
		}
		v := contractrow.DefaultTimestampValue()
		_c.mutation.SetTimestampValue(v)
	}
	if _, ok := _c.mutation.UpdatedTimestamp(); !ok {
		if contractrow.DefaultUpdatedTimestamp == nil {
			return fmt.Errorf("entfixture: uninitialized contractrow.DefaultUpdatedTimestamp (forgotten import entfixture/runtime?)")
		}
		v := contractrow.DefaultUpdatedTimestamp()
		_c.mutation.SetUpdatedTimestamp(v)
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		v := contractrow.DefaultDurationValue
		_c.mutation.SetDurationValue(v)
	}
	if _, ok := _c.mutation.EnumNumber(); !ok {
		v := contractrow.DefaultEnumNumber
		_c.mutation.SetEnumNumber(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContractRowCreate) check() error {
	if _, ok := _c.mutation.TextValue(); !ok {
		return &ValidationError{Name: "text_value", err: errors.New(`entfixture: missing required field "ContractRow.text_value"`)}
	}
	if _, ok := _c.mutation.UniqueText(); !ok {
		return &ValidationError{Name: "unique_text", err: errors.New(`entfixture: missing required field "ContractRow.unique_text"`)}
	}
	if _, ok := _c.mutation.NumericValue(); !ok {
		return &ValidationError{Name: "numeric_value", err: errors.New(`entfixture: missing required field "ContractRow.numeric_value"`)}
	}
	if _, ok := _c.mutation.TimestampValue(); !ok {
		return &ValidationError{Name: "timestamp_value", err: errors.New(`entfixture: missing required field "ContractRow.timestamp_value"`)}
	}
	if _, ok := _c.mutation.UpdatedTimestamp(); !ok {
		return &ValidationError{Name: "updated_timestamp", err: errors.New(`entfixture: missing required field "ContractRow.updated_timestamp"`)}
	}
	if _, ok := _c.mutation.DurationValue(); !ok {
		return &ValidationError{Name: "duration_value", err: errors.New(`entfixture: missing required field "ContractRow.duration_value"`)}
	}
	if _, ok := _c.mutation.EnumNumber(); !ok {
		return &ValidationError{Name: "enum_number", err: errors.New(`entfixture: missing required field "ContractRow.enum_number"`)}
	}
	return nil
}

func (_c *ContractRowCreate) sqlSave(ctx context.Context) (*ContractRow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContractRowCreate) createSpec() (*ContractRow, *sqlgraph.CreateSpec) {
	var (
		_node = &ContractRow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contractrow.Table, sqlgraph.NewFieldSpec(contractrow.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(contractrow.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(contractrow.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.PurgeTime(); ok {
		_spec.SetField(contractrow.FieldPurgeTime, field.TypeTime, value)
		_node.PurgeTime = &value
	}
	if value, ok := _c.mutation.TextValue(); ok {
		_spec.SetField(contractrow.FieldTextValue, field.TypeString, value)
		_node.TextValue = value
	}
	if value, ok := _c.mutation.UniqueText(); ok {
		_spec.SetField(contractrow.FieldUniqueText, field.TypeString, value)
		_node.UniqueText = value
	}
	if value, ok := _c.mutation.NumericValue(); ok {
		_spec.SetField(contractrow.FieldNumericValue, field.TypeInt32, value)
		_node.NumericValue = value
	}
	if value, ok := _c.mutation.NullableText(); ok {
		_spec.SetField(contractrow.FieldNullableText, field.TypeString, value)
		_node.NullableText = &value
	}
	if value, ok := _c.mutation.TimestampValue(); ok {
		_spec.SetField(contractrow.FieldTimestampValue, field.TypeTime, value)
		_node.TimestampValue = value
	}
	if value, ok := _c.mutation.UpdatedTimestamp(); ok {
		_spec.SetField(contractrow.FieldUpdatedTimestamp, field.TypeTime, value)
		_node.UpdatedTimestamp = value
	}
	if value, ok := _c.mutation.DurationValue(); ok {
		_spec.SetField(contractrow.FieldDurationValue, field.TypeInt64, value)
		_node.DurationValue = value
	}
	if value, ok := _c.mutation.EnumNumber(); ok {
		_spec.SetField(contractrow.FieldEnumNumber, field.TypeInt32, value)
		_node.EnumNumber = value
	}
	return _node, _spec
}

// ContractRowCreateBulk is the builder for creating many ContractRow entities in bulk.
type ContractRowCreateBulk struct {
	config
	err      error
	builders []*ContractRowCreate
}

// Save creates the ContractRow entities in the database.
func (_c *ContractRowCreateBulk) Save(ctx context.Context) ([]*ContractRow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContractRow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContractRowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContractRowCreateBulk) SaveX(ctx context.Context) []*ContractRow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractRowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractRowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
