// Code generated by ent, DO NOT EDIT.

package rbacpermission

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the rbacpermission type in the database.
	Label = "rbac_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeRolePermissions holds the string denoting the role_permissions edge name in mutations.
	EdgeRolePermissions = "role_permissions"
	// EdgePermissionMenus holds the string denoting the permission_menus edge name in mutations.
	EdgePermissionMenus = "permission_menus"
	// EdgePermissionApis holds the string denoting the permission_apis edge name in mutations.
	EdgePermissionApis = "permission_apis"
	// Table holds the table name of the rbacpermission in the database.
	Table = "rbac_permissions"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "rbac_permissions"
	// GroupInverseTable is the table name for the RbacPermissionGroup entity.
	// It exists in this package in order to avoid circular dependency with the "rbacpermissiongroup" package.
	GroupInverseTable = "rbac_permission_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// RolePermissionsTable is the table that holds the role_permissions relation/edge.
	RolePermissionsTable = "rbac_role_permissions"
	// RolePermissionsInverseTable is the table name for the RbacRolePermission entity.
	// It exists in this package in order to avoid circular dependency with the "rbacrolepermission" package.
	RolePermissionsInverseTable = "rbac_role_permissions"
	// RolePermissionsColumn is the table column denoting the role_permissions relation/edge.
	RolePermissionsColumn = "permission_id"
	// PermissionMenusTable is the table that holds the permission_menus relation/edge.
	PermissionMenusTable = "rbac_permission_menus"
	// PermissionMenusInverseTable is the table name for the RbacPermissionMenu entity.
	// It exists in this package in order to avoid circular dependency with the "rbacpermissionmenu" package.
	PermissionMenusInverseTable = "rbac_permission_menus"
	// PermissionMenusColumn is the table column denoting the permission_menus relation/edge.
	PermissionMenusColumn = "permission_id"
	// PermissionApisTable is the table that holds the permission_apis relation/edge.
	PermissionApisTable = "rbac_permission_apis"
	// PermissionApisInverseTable is the table name for the RbacPermissionApi entity.
	// It exists in this package in order to avoid circular dependency with the "rbacpermissionapi" package.
	PermissionApisInverseTable = "rbac_permission_apis"
	// PermissionApisColumn is the table column denoting the permission_apis relation/edge.
	PermissionApisColumn = "permission_id"
)

// Columns holds all SQL columns for rbacpermission fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldDescription,
	FieldGroupID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusACTIVE is the default value of the Status enum.
const DefaultStatus = StatusACTIVE

// Status values.
const (
	StatusACTIVE   Status = "ACTIVE"
	StatusDISABLED Status = "DISABLED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusACTIVE, StatusDISABLED:
		return nil
	default:
		return fmt.Errorf("rbacpermission: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the RbacPermission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByRolePermissionsCount orders the results by role_permissions count.
func ByRolePermissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolePermissionsStep(), opts...)
	}
}

// ByRolePermissions orders the results by role_permissions terms.
func ByRolePermissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolePermissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPermissionMenusCount orders the results by permission_menus count.
func ByPermissionMenusCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPermissionMenusStep(), opts...)
	}
}

// ByPermissionMenus orders the results by permission_menus terms.
func ByPermissionMenus(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPermissionMenusStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPermissionApisCount orders the results by permission_apis count.
func ByPermissionApisCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPermissionApisStep(), opts...)
	}
}

// ByPermissionApis orders the results by permission_apis terms.
func ByPermissionApis(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPermissionApisStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newRolePermissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolePermissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RolePermissionsTable, RolePermissionsColumn),
	)
}
func newPermissionMenusStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PermissionMenusInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PermissionMenusTable, PermissionMenusColumn),
	)
}
func newPermissionApisStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PermissionApisInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PermissionApisTable, PermissionApisColumn),
	)
}
