package main

import (
	"fmt"
	"path"
	"sort"
	"strings"

	mapperpb "github.com/Servora-Kit/servora/api/gen/go/servora/mapper/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := processFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

type messageEntry struct {
	GoName     string
	IgnoreRead []string
	FieldMap   map[string]string // entity/storage Go field -> DTO Go field
}

func processFile(gen *protogen.Plugin, f *protogen.File) error {
	var entries []messageEntry

	for _, msg := range f.Messages {
		entry := messageEntry{
			GoName:   msg.GoIdent.GoName,
			FieldMap: make(map[string]string),
		}

		hasMapperRule := proto.HasExtension(msg.Desc.Options(), mapperpb.E_Mapper)
		if hasMapperRule {
			ext := proto.GetExtension(msg.Desc.Options(), mapperpb.E_Mapper)
			rule, ok := ext.(*mapperpb.MapperRule)
			if !ok || rule == nil {
				return fmt.Errorf("%s: invalid mapper option", msg.Desc.FullName())
			}
			entry.IgnoreRead = append(entry.IgnoreRead, rule.IgnoreRead...)
		}

		for _, field := range msg.Fields {
			if !proto.HasExtension(field.Desc.Options(), mapperpb.E_MapperField) {
				continue
			}
			hasMapperRule = true
			fext := proto.GetExtension(field.Desc.Options(), mapperpb.E_MapperField)
			fr, ok := fext.(*mapperpb.MapperFieldRule)
			if !ok || fr == nil {
				return fmt.Errorf("%s: invalid mapper_field option", field.Desc.FullName())
			}
			if fr.Rename != "" {
				entry.FieldMap[fr.Rename] = field.GoName
			}
		}

		if !hasMapperRule {
			continue
		}

		entries = append(entries, entry)
	}

	if len(entries) == 0 {
		return nil
	}

	dir := path.Dir(f.GeneratedFilenamePrefix)
	baseName := path.Base(f.GeneratedFilenamePrefix)
	outFile := path.Join(dir, baseName+"_mapper.gen.go")
	g := gen.NewGeneratedFile(outFile, f.GoImportPath)
	generateMapperFile(g, f.GoPackageName, entries)
	return nil
}

func generateMapperFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, entries []messageEntry) {
	mapperPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/core/mapper")

	g.P("// Code generated by protoc-gen-servora-mapper. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	mapperConfig := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Config", GoImportPath: mapperPkg})

	for _, e := range entries {
		g.P("// ", e.GoName, "Mapper returns the read projection mapper config")
		g.P("// extracted from proto annotations on the ", e.GoName, " message.")
		g.P("func ", e.GoName, "Mapper() *", mapperConfig, " {")
		g.P("	return &", mapperConfig, "{")

		if len(e.FieldMap) > 0 {
			g.P("		FieldMapping: map[string]string{")
			for _, k := range sortedKeys(e.FieldMap) {
				v := e.FieldMap[k]
				g.P(fmt.Sprintf("			%q: %q,", k, v))
			}
			g.P("		},")
		}

		if len(e.IgnoreRead) > 0 {
			g.P("		IgnoreRead: []string{", formatStringSlice(e.IgnoreRead), "},")
		}

		g.P("	}")
		g.P("}")
		g.P()
	}
}

func formatStringSlice(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
