// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ContractRow is the predicate function for contractrow builders.
type ContractRow func(*sql.Selector)
